/*
 TeeChart(tm) for JavaScript(tm)
 @fileOverview TeeChart for JavaScript(tm)
 v1.4 December 2012
 Copyright(c) 2012 by Steema Software SL. All Rights Reserved.
 http://www.steema.com

 Licensed with commercial and non-commercial attributes,
 specifically: http://www.steema.com/licensing/html5

 JavaScript is a trademark of Oracle Corporation.
*/
var Tee=Tee||{};
(function(){"undefined"!==typeof exports&&(exports.Tee=Tee);Tee.ColorGrid=function(c,C){Tee.PaletteSeries.call(this,c,C);this.dataChanged=this.smooth=!0;var v,l,g,y,B,p,s,i,w,e,h,z,x,A,q,D,G;this.addRandom=function(r,e){for(var h,m,r=r||200,e=e||r,g=this.data.values=[],l=0;l<r;l++){h=Array(e);g[l]=h;m=Math.cos(l/(0.2*e));m=0.5*m*m;for(var i=0;i<e;i++){var n=h,p=i,c=Math.cos(i/(0.2*r));n[p]=c*c-Math.cos(i/(0.5*e))+m}}this.dataChanged=!0};this.fillPixels=function(e){for(var h=0,i,m,p=this.palette.grayScale,
c=this.palette.inverted,s=0;s<g;s++){i=v[s];for(var n=0;n<l;n++)p?(m=G*(c?q-i[n]:i[n]-A),B[h++]=m,B[h++]=m,B[h++]=m):(m=this.getColor(i[n]),B[h++]=m.r,B[h++]=m.g,B[h++]=m.b),B[h++]=e}};this.draw=function(){var r=this.chart.ctx;if(0<l){if(!y||p.width!=l||p.height!=g){p||(p=document.createElement("canvas"));if(!p||!p.getContext)return;p.width=l;p.height=g;s=p.getContext("2d");y=s.getImageData(0,0,l,g);B=y.data}this.dataChanged&&(this.fillPixels(255*(1-this.format.transparency)),this.dataChanged=!1);
s.putImageData(y,0,0);var c=this.smooth,u=this.chart.canvas.style;u&&(null!==u.getPropertyValue("image-rendering")&&u.setProperty("image-rendering",c?"optimizeQuality":"optimizeSpeed",null),void 0!==u.msInterpolationMode&&(u.msInterpolationMode=c?"bicubic":"nearest-neighbor"));r.mozImageSmoothingEnabled=c;r.webkitImageSmoothingEnabled=c;i=this.mandatoryAxis;w=this.notmandatory;x=i.calc(-0.5);h=i.calc(g-0.5);e=w.calc(-0.5);z=w.calc(l-0.5);var c=this.chart.chartRect,u=e,m=h,t=1,q=1;i.inverted&&(q=-1,
m=c.y-x-h+c.height);w.inverted&&(t=-1,u=c.x-z-e+c.width);r.scale(t,q);r.drawImage(s.canvas,0,0,l,g,u,m,z-e,x-h);c=this.format.stroke;if(""!==c.fill){m=q=1;q=Math.max(1+4*l/Math.abs(w.calc(l)-w.calc(0))|0,1);m=Math.max(1+4*g/Math.abs(i.calc(g)-i.calc(0))|0,1);r.beginPath();for(t=1;t<l;t+=q)u=w.calc(t-0.5),r.moveTo(u,x),r.lineTo(u,h);for(t=1;t<g;t+=m)u=i.calc(t-0.5),r.moveTo(e,u),r.lineTo(z,u);c.prepare();r.stroke()}}};this.valueText=function(h){return this.data.values[h/l|0][h%l].toFixed(this.decimals)};
this.minXValue=function(){return-0.5};this.maxXValue=function(){return l-0.5};this.minYValue=function(){return-0.5};this.maxYValue=function(){return g-0.5};this.recalcAxes=function(){Tee.Series.prototype.recalcAxes.call(this);v=this.data.values;g=v.length;l=0<g?v[0].length:0;this.size={x:l,y:g};if(0<l&&this.dataChanged){q=A=v[0][0];for(var h,e,c=0;c<g;c++){e=v[c];for(var i=0;i<l;i++)h=e[i],h<A?A=h:h>q&&(q=h)}D=q-A;G=q==A?1:255/(q-A);this._min=A;this._max=q;this._range=D;this.prepareColors()}};this.clicked=
function(c){var i;return c.x>=e&&c.x<=z&&(i=l*(c.x-e)/(z-e)|0,c.y>=h&&c.y<=x)?(c=g*(c.y-h)/(x-h)|0,c*l+i):-1}};Tee.ColorGrid.prototype=new Tee.PaletteSeries;Tee.Surface=function(c,C){Tee.ColorGrid.call(this,c,C);var v;this.grid=(new Tee.Format(c)).stroke;this.wireFrame=!1;this.maxZ=3;this.getY=function(c,g){return v[c][g]};this.draw=function(){if(0<this.size.x&&0<this.size.y&&(v=this.data.values,this.chart.__webgl)){var c={};this.bounds(c);this.chart.ctx.surface(this.size,this.getY,c,this.wireFrame,
this.grid.visible?this.grid.fill:null,this.maxZ)}};this.minXValue=function(){return 0};this.maxXValue=function(){return this.size.y};this.minYValue=function(){return this._min};this.maxYValue=function(){return this._max}};Tee.Surface.prototype=new Tee.ColorGrid;Tee.MyTorusGeometry=function(c,C,v,l,g){THREE.Geometry.call(this);this.radius=c||100;this.tube=C||40;this.radialSegments=v||8;this.tubularSegments=l||6;this.arc=g||2*Math.PI;for(var y,B=2*1/this.radialSegments*Math.PI,p=1/this.tubularSegments*
this.arc,s,i,w,e,h,C=this.vertices,v=[],l=[],c=0;c<=this.radialSegments;c++){g=c*B;i=s=this.radius+this.tube*Math.cos(g);w=this.tube*Math.sin(g);h=c/this.radialSegments;for(g=0;g<=this.tubularSegments;g++){y=g*p;e=Math.cos(y);y=Math.sin(y);var z=new THREE.Vector3(s*e,i*y,w);C.push(z);v.push(new THREE.UV(g/this.tubularSegments,h));e=new THREE.Vector3(z.x-this.radius*e,z.y-this.radius*y,w);l.push(e.normalize())}}for(var B=this.tubularSegments+1,x,A,q,D,G=0,r=0,I,c=1;c<=this.radialSegments;c++){p=G=
r+B;s=r;x=l[p];A=l[s];y=C[p];z=C[s];for(g=1;g<=this.tubularSegments;g++)i=r+g,w=G+g,h=l[i],e=l[w],I=new THREE.Face4(p,s,i,w,[x,A,h,e]),q=I.normal,q.x=x.x+A.x+h.x+e.x,q.y=x.y+A.y+h.y+e.y,q.z=x.z+A.z+h.z+e.z,q.normalize(),x=I.centroid,q=C[i],D=C[w],x.x=0.25*(y.x+z.x+q.x+D.x),x.y=0.25*(y.y+z.y+q.y+D.y),x.z=0.25*(y.z+z.z+q.z+D.z),this.faces.push(I),this.faceVertexUvs[0].push([v[p],v[s],v[i],v[w]]),p=w,s=i,x=e,A=h,y=D,z=q;r+=B}};"undefined"!==typeof THREE&&(Tee.MyTorusGeometry.prototype=new THREE.Geometry);
Tee.MyParametricGeometry=function(c,C,v,l){THREE.Geometry.call(this);var g=this.vertices,y=this.faces,B=this.faceVertexUvs[0],l=void 0===l?!1:l,p,s,i=C+1,w=1/C,e=1/i,h=1/v,z=1/(v+1);for(p=0;p<=v;p++)for(s=0;s<=C;s++)g.push(new THREE.Vector3(p*h-0.5,c(p,s),0.5-s*w));var x,A,q,D,G,r,I,u;for(p=0;p<v;p++){G=p*z;r=(p+1)*z;I=p*i;u=(p+1)*i;for(s=0;s<C;s++)c=I+s,g=u+s,q=s*e,x=q+e,w=new THREE.UV(q,G),h=new THREE.UV(x,G),q=new THREE.UV(q,r),D=new THREE.UV(x,r),l?(x=c+1,A=g+1,y.push(new THREE.Face3(c,x,g)),
y.push(new THREE.Face3(x,A,g)),B.push([w,h,q]),B.push([h,D,q])):(y.push(new THREE.Face4(c,c+1,g+1,g)),B.push([w,h,D,q]))}this.computeCentroids();this.computeFaceNormals();this.computeVertexNormals()};"undefined"!==typeof THREE&&(Tee.MyParametricGeometry.prototype=new THREE.Geometry);var K="undefined"!==typeof HTMLCanvasElement;Tee.Three=function(c){function C(a,b,d,j,k,f,c,e){a&&(b=new THREE.MeshBasicMaterial({vertexColors:THREE.VertexColors}),b.wireframe=a);b.vertexColors=THREE.VertexColors;a||(b.side=
THREE.DoubleSide);a=new THREE.Mesh(k,b);k=e-c;e===c&&(k=1);e=j.height/k;a.position.set(j.x+0.5*(j.width-m),j.y+0.5*(j.height-t)-(c+0.5*k)*e,0.5*-i);a.scale.set(j.width,e,i*f);h.add(a)}function v(a){r.extrudeOptions.amount=i*r.depth;a=0==r.depth?new THREE.ShapeGeometry(a):a.extrude(r.extrudeOptions);a=THREE.SceneUtils.createMultiMaterialObject(a,[r.getMaterial()]);r.showShadows&&(a.receiveShadow=!0,a.castShadow=!0);return a}function l(a,b,d,j,k,f){a.moveTo(b,d+f);a.lineTo(b,d+k-f);a.quadraticCurveTo(b,
d+k,b+f,d+k);a.lineTo(b+j-f,d+k);a.quadraticCurveTo(b+j,d+k,b+j,d+k-f);a.lineTo(b+j,d+f);a.quadraticCurveTo(b+j,d,b+j-f,d);a.lineTo(b+f,d);a.quadraticCurveTo(b,d,b,d+f)}function g(a){if("rgb("==a.substr(0,4))return a=a.slice(4,a.length-1).split(","),a[2]|a[1]<<8|a[0]<<16;switch(a){case "white":return 16777215;case "silver":return 14737632;case "darkgray":case "darkgrey":return 8421504;case "black":return 0;case "red":return 16711680;case "green":return 65280;case "blue":return 255;default:return 16777215}}
function y(a,b){var d=u;d.width=a;d.height=b;n.setSize(a,b);E.aspect=a/b;E.updateProjectionMatrix()}function B(){p?(y(s.width,s.height),p=!1):(s.width=u.width,s.height=u.height,y(window.innerWidth,window.innerHeight),p=!0);r.refresh()}this.setEnabled=function(a,b){if(!a||!Detector||Detector.webgl){if(this.__webgl=a)n&&(b.__webgl=!0,b.canvas.style.display="none",b.canvas=this,b.ctx=this,n&&n.domElement&&(n.domElement.style.display="block"));else{var d=u;e||(K?(e=document.createElement("canvas"),d instanceof
HTMLCanvasElement?(d.parentElement.appendChild(e),e.style.background=d.style.background):d.appendChild(e)):"undefined"!=typeof G_vmlCanvasManager&&(e=document.createElement("canvas"),e=G_vmlCanvasManager.initElement(e),d.appendChild(e)));e&&(e.setAttribute("width",d.width),e.setAttribute("height",d.height),e.height=d.clientHeight,e.width=d.clientWidth);n&&n.domElement?n.domElement.style.display="none":K&&d instanceof HTMLCanvasElement&&(d.style.display="none");e&&(e.style.display="block");b.canvas=
e;b.ctx=null;b.__webgl=null;b.bounds.set(0,0,e.width,e.height);e&&(e.chart=b,e.onmousedown=e.ontouchstart=b.domousedown,e.onmouseup=e.ontouchstop=b.domouseup,e.onmousemove=e.ontouchmove=b.domousemove,e.onmousewheel=e.onmousewheel=b._doWheel)}H&&(H.enabled=a);b.aspect.view3d=a;b.draw()}};this.zPos=function(){return i*(1-this.z-0.5*this.depth)};this.Gradient=function(){this.colors=[];this.stops=[];this.addColorStop=function(a,b){this.stops.push(a);this.colors.push(b)}};this.clearRect=function(){h&&
(F.remove(h),h.deallocate());h=new THREE.Object3D;F.add(h);this.needsRender=!0};this.beginPath=function(){this.items=[];this.closedPath=!1};this.moveTo=function(a,b,d){this.items.push({kind:0,x:a,y:b,z:d})};this.lineTo=function(a,b,d){this.items.push({kind:1,x:a,y:b,z:d})};this.lineZ=function(a,b,d,j){this.moveTo(a,b,d);this.lineTo(a,b,j)};this.surface=function(a,b,d,j,k,f){b=new Tee.MyParametricGeometry(b,a.x-1,a.y-1,!1);b.computeBoundingBox();var c=b.boundingBox,h=c.min.y,c=c.max.y,e=c-h,i,g,l=
["a","b","c","d"],m=b.vertices;for(g=0;g<b.vertices.length;g++)i=new THREE.Color,i.setHSV(0.7*(c-m[g].y)/e,1,0.9),b.colors[g]=i;for(g=0;g<b.faces.length;g++){e=b.faces[g];for(i=0;4>i;i++)e.vertexColors[i]=b.colors[e[l[i]]]}g=new THREE.MeshLambertMaterial({color:16777215,opacity:this.globalAlpha,wireframe:this.wireframe});C(j,g,a,d,b,f,h,c);k&&!j&&(j=new THREE.MeshBasicMaterial({color:this.colorToInt(k),opacity:this.globalAlpha}),j.wireframe=!0,C(!1,j,a,d,b,f,h,c))};this.slice=function(a,b,d,j,k,f,
c,e){this.beveled=void 0===e?!1:e;0<f?(this.path=8,this.p=a,this.torus=c,this.center=b,this.radius=d,this.angle0=j,this.angle1=k,this.donut=f,this.items=[]):(this.beginPath(),this.moveTo(a.x,a.y),this.arc(b.x,b.y,d,j,k,!1),this.closePath())};this.closePath=function(){this.closedPath=!0};this.createLinearGradient=function(){return new this.Gradient};this.createRadialGradient=function(){return new this.Gradient};this.getMaterial=function(){return new THREE.MeshPhongMaterial({color:this.colorToInt(this.fillStyle),
opacity:this.globalAlpha,wireframe:this.wireframe,specular:5592405,map:null})};this.spline=function(a,b){this.items=[];var d=this.path=0;if(b){for(var j=[];d<a.length;)j.push(new THREE.Vector2(a[d],-a[d+1])),d+=2;this.items.push({kind:12,p:j})}else{for(j=new THREE.SplineCurve3;d<a.length;)j.points.push(new THREE.Vector3(a[d],-a[d+1],0)),d+=2;this.items.push({kind:8,geo:j})}};this.bezierCurveTo=function(a,b,d,j,k,f){this.items.push({kind:11,a:a,b:b,c:d,d:j,e:k,f:f})};this.quadraticCurveTo=function(a,
b,d,j){this.items.push({kind:7,x:a,y:b,width:d,height:j})};this.arc=function(a,b,d,j,k,f){this.items.push({kind:4,x:a,y:b,radius:d,angle:j,endAngle:k,clockwise:f})};this.extrudeOptions={amount:1,bevelEnabled:!1,bevelSegments:16,steps:12,curveSegments:64,bevelThickness:10,bevelSize:8};this.getContext=function(){return this};this.beginParent=function(){z=h;h=new THREE.Object3D;z.add(h);return h};this.endParent=function(){h=z};this.fill=function(){var a,b;b=r.getMaterial();var d=this.items,j=d.length,
k=this.r;if(0<j)if(8==d[0].kind)d=new THREE.TubeGeometry(d[0].geo,100,0.05*i*this.depth,8,!1,!1),b=new THREE.Mesh(d,b),b.position.set(0.5*-m,0.5*t,this.zPos()),h.add(b);else if(this.closedPath){b=new THREE.Shape;for(var f,c,e,g=0;g<j;g++)if(f=d[g],0==f.kind){if(0==g||c!==f.x||e!==-f.y)c=f.x,e=-f.y,b.moveTo(c,e)}else if(1==f.kind){if(0==g||c!==f.x||e!==-f.y)c=f.x,e=-f.y,b.lineTo(c,e)}else 4==f.kind?b.absarc(c,e,f.radius,2*Math.PI-f.angle,2*Math.PI-f.endAngle,f.clockwise):7==f.kind?b.quadraticCurveTo(f.x,
f.y,f.width,f.height):11==f.kind?b.bezierCurveTo(f.a,-f.b,f.c,-f.d,f.e,-f.f):12==f.kind&&(b.moveTo(f.p[0].x,f.p[0].y),b.splineThru(f.p));d=this.extrudeOptions.bevelEnabled;if(this.extrudeOptions.bevelEnabled=this.beveled)j=0.02*this.extrudeOptions.bevelSize,this.depth-=j,this.z+=0.5*j;b=v(b);b.position.set(0.5*-m,0.5*t,this.zPos()-0.5*i*this.depth);h.add(b);this.extrudeOptions.bevelEnabled=d}else{e=new THREE.Geometry;c=-i*this.depth;b.side=THREE.DoubleSide;for(g=0;g<j;g++)e.vertices.push(new THREE.Vector3(d[g].x,
-d[g].y,0),new THREE.Vector3(d[g].x,-d[g].y,c)),0<g&&(f=new THREE.Face4(2*(g-1),2*g-1,2*g+1,2*g),e.faces.push(f));e.computeFaceNormals();b=new THREE.Mesh(e,b);b.position.set(0.5*-m,0.5*t,this.zPos()-0.5*c);h.add(b)}else 0==this.depth?0<this.rx?(b=new THREE.Shape,l(b,k.x,-k.y,k.width,k.height,this.rx),b=v(b),b.position.set(0.5*-m,-k.height+0.5*t,this.zPos()),h.add(b)):6==this.path?(b=new THREE.Shape,b.absellipse(0,0,0.5*k.width,0.5*k.height,0,2*Math.PI,!0),b=v(b),b.position.set(this.cx-0.5*m,-this.cy+
0.5*t,this.zPos()),h.add(b)):(a=new THREE.PlaneGeometry(k.width,k.height),b.side=THREE.DoubleSide,a=new THREE.Mesh(a,b)):5==this.path?(1==this.topRadius?(A||(A=new THREE.CylinderGeometry(1,1,1,32,1,!1)),a=A):(q||(q=new THREE.CylinderGeometry(0,1,1,32,1,!1)),a=q),a=new THREE.Mesh(a,b),b=0.5*Math.min(this.vertical?k.width:k.height,i),a.scale.x=b,a.scale.z=b,a.scale.y=this.vertical?k.height:k.width,this.vertical||(a.rotation.z=0.5*Math.PI,a.rotation.y=Math.PI)):6==this.path?(b=new THREE.Shape,b.absellipse(0,
0,0.5*k.width,0.5*k.height,0,2*Math.PI,!0),b=v(b),b.position.set(this.cx-0.5*m,-this.cy+0.5*t,this.zPos()),h.add(b)):8==this.path?(this.angle0=2*Math.PI-this.angle0,this.angle1=2*Math.PI-this.angle1,this.torus?(d=Math.abs(this.angle1-this.angle0),j=Math.max(16,90*Math.PI/d|0),d=new Tee.MyTorusGeometry(this.radius-0.5*this.donut,0.5*this.donut,16,j,d),b=new THREE.Mesh(d,b),b.position.set(this.center.x-0.5*m,-this.center.y+0.5*t,this.zPos()+this.donut),b.rotation.z=this.angle1,h.add(b)):(b=new THREE.Shape,
b.moveTo(this.p.x,this.p.y),b.absarc(this.center.x,this.center.y,this.radius,this.angle0,this.angle1,!0),b.absarc(this.center.x,this.center.y,this.donut,this.angle0,this.angle1,!1),d=this.extrudeOptions.bevelEnabled,this.extrudeOptions.bevelEnabled=this.beveled,b=v(b),b.position.set(0.5*-m,0.5*-t,this.zPos()),h.add(b),this.extrudeOptions.bevelEnabled=d)):(1===w?(D||(D=new THREE.CubeGeometry(1,1,1)),a=D):(G||(G=new THREE.CubeGeometry(1,1,1,w,w,w),(new THREE.SubdivisionModifier(2)).modify(G)),a=G),
a=new THREE.Mesh(a,b),a.scale.set(k.width,k.height,i*this.depth));a&&(a.position.set(k.x+0.5*k.width-0.5*m,-(k.y+0.5*k.height)+0.5*t,this.zPos()),this.showShadows&&(a.receiveShadow=!0,a.castShadow=!0),h.add(a))};this.setLineDash=function(a){this.dash=a};this.lineMaterial=function(){var a;a={color:this.colorToInt(this.strokeStyle),opacity:this.globalAlpha};this.dash&&0<this.dash.length?(a=new THREE.LineDashedMaterial(a),a.dashSize=3,a.gapSize=1):(a=new THREE.LineBasicMaterial(a),a.linecap=this.cap,
a.linejoin=this.join);a.linewidth=this.lineWidth;return a};this.polygon=function(a,b){var d,j=a.length,c,f,e=new THREE.Shape;e.moveTo(a[0].x,-a[0].y);for(d=1;d<j;d++)c=a[d],e.lineTo(c.x,-c.y);f=e.makeGeometry();""!==b.fill&&(this.fillStyle=b.fill,0<this.depth?d=v(e):(c=this.getMaterial(),d=new THREE.Mesh(f,c),this.wireFrame||(c.side=THREE.DoubleSide)),f=i*(1-this.z),d.position.set(0.5*-m,0.5*t,f-0.5*this.depth),this.showShadows&&(d.castShadow=!0),h.add(d));if(""!==b.stroke.fill){f=new THREE.Geometry;
for(d=0;d<j;d++)c=a[d],f.vertices.push(new THREE.Vector3(c.x,-c.y,0));j=new THREE.Line(f,this.lineMaterial());f=i*(1-this.z+this.depth);j.position.set(0.5*-m,0.5*t,f);h.add(j)}};this.stroke=function(){var a=this.items.length,b=this.lineMaterial(),d;if(0<a){var c,e;e=new THREE.Geometry;for(var f=0;f<a;f++)c=this.items[f],d=void 0===c.z?this.z:c.z,d=i*(1-d),0==c.kind?(0<e.vertices.length&&(e=new THREE.Line(e,b),h.add(e)),e=new THREE.Geometry,e.vertices.push(new THREE.Vector3(c.x-0.5*m,-c.y+0.5*t,d))):
1==c.kind&&e.vertices.push(new THREE.Vector3(c.x-0.5*m,-c.y+0.5*t,d));0<e.vertices.length&&(e=new THREE.Line(e,b),h.add(e))}else 0==this.depth&&(a=new THREE.Path,d=this.r,0==this.path||1==this.path?0<this.rx?l(a,d.x,-d.y-d.height,d.width,d.height,this.rx):(a.moveTo(d.x,-d.y-d.height),a.lineTo(d.x+d.width,-d.y-d.height),a.lineTo(d.x+d.width,-d.y),a.lineTo(d.x,-d.y)):6==this.path&&a.absellipse(this.cx,-this.cy,0.5*d.width,0.5*d.height,0,2*Math.PI,!0),e=new THREE.Line(a.createPointsGeometry(),b),e.position.set(0.5*
-m,0.5*t,this.zPos()),h.add(e))};this.measureText=function(a){return{width:1.4*M.measureText(a).width}};this.roundRect=function(a,b,d,c,e,f){this.path=0;this.r={x:a,y:b,width:d,height:c};this.depth=0;this.rx=e;this.ry=f};this.rect=function(a,b,d,c){this.path=0;this.r={x:a,y:b,width:d,height:c};this.ry=this.rx=this.depth=0};this.cube=function(a,b){this.path=1;this.r=a;this.items=[];w=0<b?6:1};this.sphere=function(a,b,d,c){x||(x=new THREE.SphereGeometry(1,32,32));var e=new THREE.Mesh(x,this.getMaterial());
e.position.set(a-0.5*m,-b+0.5*t,this.zPos());e.scale.set(0.5*d,0.5*c,0.5*Math.min(d,i));h.add(e)};this.save=function(){};this.clip=function(){};this.restore=function(){};this.colorToInt=function(a){a=a instanceof this.Gradient?a.colors[a.colors.length-1]:a;return"#"==a.substr(0,1)?parseInt(a.substr(1),16):g(a)};this.pyramid=function(){var a=[new THREE.Vector3(100,0,0),new THREE.Vector3(0,100,0),new THREE.Vector3(0,0,100),new THREE.Vector3(0,0,0)];new THREE.ConvexGeometry(a)};this.cylinder=function(a,
b,d){this.path=5;this.r=a;this.topRadius=b;this.vertical=d;this.items=[]};this.ellipsePath=function(a,b,d,c){this.path=6;this.cx=a;this.cy=b;this.r={x:a,y:b,width:d,height:c};this.items=[]};this.addLight=function(a,b,d,c,e,f){a=new a(b);a.position.set(d,c,e);a.shadowsEnabled=f;if(this.showShadows&&f&&(a instanceof THREE.SpotLight||a instanceof THREE.DirectionalLight))a.castShadow=!0;F.add(a);this.lights.push(a);return a};this.fillText=function(a,b,d){if(""!==a){var c;a:{var e=this.font.split(" "),
f;for(f=0;f<e.length;f++)if(c=parseFloat(e[f]))break a;c=20}a:{f=I.length;for(var g,e=0;e<f;e++)if(g=I[e],g.text===a&&g.size===c){f=g.obj;break a}f=null}e=0;f||(f=new THREE.TextGeometry(a,{size:c,height:this.textDepth,curveSegments:2,font:"helvetiker"}),f.computeBoundingBox(),I.push({text:a,obj:f,size:c}));a=f.boundingBox;c=a.max.x-a.min.x;a=a.max.y-a.min.y;if("center"===this.textAlign)e=-0.5*c;else if("right"===this.textAlign||"end"===this.textAlign)e=-c;c=new THREE.MeshLambertMaterial({color:this.colorToInt(this.fillStyle),
opacity:this.globalAlpha,overdraw:!1});f=new THREE.Mesh(f,c);a="top"===this.textBaseline?a:"middle"==this.textBaseline?0.5*a:0;f.position.x=b+e-0.5*m;f.position.y=-d+0.5*t-a;f.position.z=1+i*(1-this.z);f.rotation.x=0;f.rotation.y=2*Math.PI;h.add(f)}};this.update=function(){this.__webgl&&(H&&H.enabled&&H.update(1),this.needsRender&&(this.hitTest&&this.doHitTest(),this.doRender()))};this.setCamera=function(a){E&&F.remove(E);this.camera=E=a?new THREE.PerspectiveCamera(45,window.innerWidth/window.innerHeight,
0.1,1E4):new THREE.OrthographicCamera(-window.innerWidth/2,window.innerWidth/2,window.innerHeight/2,-window.innerHeight/2,0.1,1E4);E.lookAt(F.position);F.add(E);E.position.set(0,0,800);H&&(H.object=E);this.refresh()};this.refresh=function(){this.needsRender=!0;this.update()};this.createTrackball=function(){if(n&&"undefined"!==typeof THREE.TrackballControls){H=this.trackBall=new THREE.TrackballControls(E,n.domElement);H.enabled=!0;H.keys=[65,83,68];H.dynamicDampingFactor=0.2;if(-1<("undefined"!=typeof navigator?
navigator.userAgent.toLowerCase():"").indexOf("mac os x"))H.zoomSpeed=0.1;H instanceof THREE.TrackballControls&&H.addEventListener("change",function(){r.needsRender=!0})}};var p,s={};document.addEventListener("fullscreenchange",B,!1);document.addEventListener("mozfullscreenchange",B,!1);document.addEventListener("webkitfullscreenchange",B,!1);this.fullScreen=function(){var a=u,b=a.requestFullscreen||a.mozRequestFullscreen||a.webkitRequestFullscreen||a.msRequestFullScreen;b&&b.call(a)};this.onWindowResize=
function(){E instanceof THREE.PerspectiveCamera&&(E.aspect=window.innerWidth/Math.max(1,window.innerHeight));E.updateProjectionMatrix();n&&n.setSize(window.innerWidth,window.innerHeight)};this.setShowShadows=function(a){this.showShadows=a;for(var b,a=0;a<this.lights.length;a++)if(b=this.lights[a],(b instanceof THREE.SpotLight||b instanceof THREE.DirectionalLight)&&b.shadowsEnabled)b.castShadow=this.showShadows;L.receiveShadow=this.showShadows;if(n&&(n.shadowMapEnabled=this.showShadows,n.shadowMapSoft=
this.showShadows))n.shadowMapAutoUpdate=!0};this.setShowLights=function(a){this.showLights=a;var b,d=this.lights.length,c;for(b=0;b<d;b++)if(c=this.lights[b],c.__helper)a=c.visible&&this.showLights,c.__helper.traverse(function(b){b.visible=a});else if(this.showLights){if(c instanceof THREE.SpotLight)c.__helper=new THREE.SpotLightHelper(c,16,100);else if(c instanceof THREE.PointLight)c.__helper=new THREE.PointLightHelper(c,16);else if(c instanceof THREE.DirectionalLight)c.__helper=new THREE.DirectionalLightHelper(c,
16,100);else continue;F.add(c.__helper)}this.needsRender||this.refresh()};this.showLight=function(a,b){var c=this.lights[a];c.visible=b;c.__helper&&(b=b&&this.showLights,c.__helper.traverse(function(a){a.visible=b}));this.refresh()};this.doHitTest=function(){};this.doRender=function(){n&&(n.render(F,E),n.shadowMapAutoUpdate=!1,J&&J.visible&&J.update());this.needsRender=!1};this.clearTextCache=function(){I=[]};this.toogle=function(a,b){a.visible=b;a.visual?(a.visual.traverse(function(a){a.visible=
b}),this.needsRender=!0):a.chart.draw();this.update()};this.isEnabled=function(){return this.__webgl};this.__webgl="undefined"===typeof Detector||Detector&&Detector.webgl;this.needsRender=!0;var i=200;this.showShadows=this.showLights=!1;this.items=[];this.closedPath=!1;this.textDepth=this.z=0;this.beveled=!1;var w=1,e,h;this.wireframe=!1;this.globalAlpha=1;var z,x,A,q,D,G,r=this,I=[],u=document.getElementById(c),m=u.clientWidth,t=u.clientHeight,F,E,n,c=null;K&&u instanceof HTMLCanvasElement&&(c=u);
this.__webgl&&(F=new THREE.Scene,n=new THREE.WebGLRenderer({antialias:!0,canvas:c,clearAlpha:1}));var M=null;K&&(M=document.createElement("canvas").getContext("2d"));this.width=m;this.height=t;this.camera=E;this.scene=F;(this.renderer=n)?n.sortObjects=!1:this.__webgl=!1;var J=this.stats=null;document.addEventListener&&"undefined"!==typeof Stats&&(J=this.stats=new Stats,J.visible=!0,J.setVisible=function(a){J.visible=a;J.domElement.style.display=a?"block":"none"});n&&(F.fog=new THREE.Fog(10066329,
5E3,1E4),n.setSize(m,t),this.showShadows&&(n.shadowMapEnabled=!0,n.shadowMapSoft=!0));F&&F.add(E);c="#AAAA77";window.getComputedStyle&&(c=window.getComputedStyle(u).backgroundColor);n&&(n.setClearColorHex(this.colorToInt(c),1),u!==n.domElement&&u.appendChild(n.domElement));this.lights=[];if(n){this.addLight(THREE.SpotLight,8947848,-300,300,400,!0);this.addLight(THREE.DirectionalLight,11184810,400,1800,1600,!1);this.addLight(THREE.PointLight,8947848,500,120,-500,!1);this.setShowLights(this.showLights);
c=this.ambientLight=new THREE.AmbientLight(2236962);c.visible=!1;F.add(c);var L=this.floor=new THREE.Mesh(new THREE.CylinderGeometry(4E3,4E3,50,32,1,!1),new THREE.MeshLambertMaterial({color:this.colorToInt("silver"),map:null,opacity:0.9,transparent:!0}));this.showShadows&&(L.receiveShadow=!0);L.position.y=-20-0.5*t;F.add(L);var H=this.trackBall=null;this.createTrackball();this.setCamera(!0)}this.needsRender=!0}}).call(this);
