/*
 TeeChart(tm) for JavaScript(tm)
 @fileOverview TeeChart for JavaScript(tm)
 v1.4 December 2012
 Copyright(c) 2012 by Steema Software SL. All Rights Reserved.
 http://www.steema.com

 Licensed with commercial and non-commercial attributes,
 specifically: http://www.steema.com/licensing/html5

 JavaScript is a trademark of Oracle Corporation.
*/
var Tee=Tee||{};
(function(){function m(a,d){this.x=a;this.y=d}function P(a,d,b,e){function c(){var e,c;if(b.x==d.x&&b.y==d.y)e=a.x-d.x,c=a.y-d.y;else{e=b.x-d.x;c=b.y-d.y;var g=((a.x-d.x)*e+(a.y-d.y)*c)/(e*e+c*c);0>g?(e=a.x-d.x,c=a.y-d.y):1<g?(e=a.x-b.x,c=a.y-b.y):(e=a.x-(d.x+g*e),c=a.y-(d.y+g*c))}return Math.sqrt(e*e+c*c)}return a.x==d.x&&a.y==d.y||a.x==b.x&&a.y==b.y?!0:Math.abs(c())<=e+1}function n(a,d,b,e){this.set(a,d,b,e)}function K(){this.left=this.right=this.top=this.bottom=2;this.apply=function(a){var d=a.width,
b=a.height;a.x+=0.01*d*this.left;a.width-=0.01*d*Math.min(100,this.left+this.right);a.y+=0.01*b*this.top;a.height-=0.01*b*Math.min(100,this.top+this.bottom)}}function Q(a,d,b){this.format=b;this.bounds=d;var e=this,d=b.shadow;this.old=new A;this.old.set(d);d.visible=!0;d.color="rgba(0,255,0,0.1)";d.blur=10;d.width=0;d.height=0;this.enabled=!0;b=new Tee.Animation(b.chart,function(b){e.enabled&&(1>b?e.format.shadow.color="rgba(0,255,0,"+b.toString()+")":e.autoHide&&e.restore())});b.duration=a;b.animate();
this.restore=function(){this.format.shadow.set(this.old);this.enabled=!1}}function z(a){this.chart=a;this.visible=!1;this.colors=["white","silver"];this.direction="topbottom";this.stops=null;this.offset={x:0,y:0};this.create=function(a,b){return this.rect(a.x,a.y,a.width,a.height,b)};this.rect=function(a,b,e,c,f){var h;h=this.chart.ctx;var g=h.createLinearGradient;"topbottom"==this.direction?h=g.call(h,a,b,a,b+c):"bottomtop"==this.direction?h=g.call(h,a,b+c,a,b):"leftright"==this.direction?h=g.call(h,
a,b,a+e,b):"rightleft"==this.direction?h=g.call(h,a+e,b,a,b):"radial"==this.direction?(a=a+0.5*e+this.offset.x,b=b+0.5*c+this.offset.y,e=Math.max(e,c),h=h.createRadialGradient(a,b,0,a,b,e)):h="diagonalup"==this.direction?g.call(h,a,b+c,a+e,b):g.call(h,a,b,a+e,b+c);f&&this.setEndColor(f);e=this.colors;c=e.length;a=(b=this.stops)?b.length:0;if(1<c)for(f=0;f<c;f++)h.addColorStop(a<=f?f/(c-1):b[f],e[f]);else h.addColorStop(0,0<c?e[0]:"white");return h}}function A(a){this.chart=a;this.visible=!1;this.blur=
4;this.color="rgba(80,80,80,0.75)";this.height=this.width=4;this.prepare=function(a){this.visible?(a.shadowBlur=this.blur,a.shadowColor=this.color,a.shadowOffsetX=this.width,a.shadowOffsetY=this.chart.isAndroid?-this.height:this.height):a.shadowColor="transparent"}}function L(a){this.url="";this.chart=a;this.visible=!0;this.tryDraw=function(d,b,e,c){this.image||(this.image=new Image,this.image.onload=function(){a.draw()});""===this.image.src?(a=this.chart,this.image.src=this.url):a.ctx.drawImage(this.image,
d,b,e,c)}}function B(a){this.chart=a;this.fill="black";this.size=1;this.join="round";this.cap="square";this._g=this.dash=null;v?v(this,"gradient",{get:function(){this._g||(this._g=new z(this.chart));return this._g}}):this._g=this.gradient=new z(a);this.prepare=function(a,b){var b=b||this.chart.ctx,e=this._g;b.strokeStyle=e&&e.visible?e.create(this.chart.bounds):a?a:this.fill;b.lineWidth=this.size;b.lineJoin=this.join;b.lineCap=this.cap;b.shadowColor="transparent";b.setLineDash?b.setLineDash(this.dash||
[]):b.mozCurrentTransform?b.mozDash=this.dash:this.chart.isChrome&&(b.webkitLineDash=this.dash)};this.setChart=function(a){this.chart=a;this._g&&(this._g.chart=a)}}function C(a){this.chart=a;this.style="11px Tahoma";this._g=null;v?v(this,"gradient",{get:function(){this._g||(this._g=new z(this.chart));return this._g}}):this._g=this.gradient=new z(a);this.fill="black";this._sh=null;v?v(this,"shadow",{get:function(){this._sh||(this._sh=new A(this.chart));return this._sh}}):this._sh=this.shadow=new A(a);
this._s=null;v?v(this,"stroke",{get:function(){this._s||(this._s=new B(this.chart),this._s.fill="");return this._s}}):(this._s=this.stroke=new B(a),this._s.fill="");this.textAlign="center";this.baseLine="alphabetic"}function R(a){this.chart=a;this.items=[];this.draw=function(){for(var a=0,b;b=this.items[a++];)b.active&&b.draw()};this.mousemove=function(a){for(var b=0,e;e=this.items[b++];)e.active&&e.mousemove(a)};this.mousedown=function(a){for(var b=0,e,c=!1;e=this.items[b++];)e.active&&e.mousedown(a)&&
(c=!0);return c};this.mouseout=function(){for(var a=0,b;b=this.items[a++];)b.active&&b.mouseout()};this.clicked=function(a){for(var b=this.items.length,e,c=!1;e=this.items[--b];)e.active&&e.clicked(a)&&(c=!0,e.onclick&&(c=e.onclick(e,a.x,a.y)));return c};this.add=function(a){this.items.push(a);return a}}function S(a){function d(b){var a=b.chart.chartRect,d=b.direction,g="both"===d;e.set(a.x,a.y,a.width,a.height);if(b.old){if(g||"horizontal"===d)0>b.old.x?(e.x=b.chart.oldPos.x+b.old.x,e.width=-b.old.x):
(e.x=b.chart.oldPos.x,e.width=b.old.x);if(g||"vertical"===d)0>b.old.y?(e.y=b.chart.oldPos.y+b.old.y,e.height=-b.old.y):(e.y=b.chart.oldPos.y,e.height=b.old.y)}return e}this.chart=a;this.active=!1;this.enabled=!0;this.done=!1;this.direction="both";this.keepAspect=!1;this.mouseButton=0;this.wheel={enabled:!1,factor:1};var b=this.format=new Tee.Format(a);b.fill="rgba(255,255,255,0.5)";b.stroke.fill="darkgray";b.stroke.size=2;var e=new n;this.change=function(b){this.old||(this.old=new m);var a=this.chart.oldPos;
this.old.x=b.x-a.x;this.keepAspect?(b=this.chart.chartRect,this.old.y=this.old.x*(b.height/b.width)):this.old.y=b.y-a.y};this.draw=function(){b.rectangle(d(this))};this.apply=function(){if(0>this.old.x||0>this.old.y){if(this.reset(),this.onreset)this.onreset()}else if(d(this),3<e.width&&3<e.height){var b=this.direction,a="both"===b;this.chart.axes.each(function(){this.horizontal?(a||"horizontal"===b)&&this.calcMinMax(e.x,e.x+e.width):(a||"vertical"===b)&&this.calcMinMax(e.y+e.height,e.y)});return!0}return!1};
this.reset=function(){this.chart.axes.each(function(){this.automatic=!0})}}function T(a){this.chart=a;this.active=!1;this.enabled=!0;this.done=!1;this.mouseButton=2;this.direction="both";this.position=new m(0,0)}function I(a,d){Tee.Annotation.call(this,a);this.transparent=!0;this._expand=!1;v?v(this,"expand",{get:function(){return this._expand},set:function(b){this._expand=b;this._expand||(b=this.format,b.round.x=8,b.round.y=8,b.round.corners=null,b.stroke.fill="black")}}):this._expand=this.expand=
!1;var b=this.format.font,e=b.shadow,c=this.position;e.visible=!0;e.width=2;e.height=2;e.blur=8;b.style="18px Tahoma";b.fill=d;this.padding=4;this.calcRect=function(b){this.resize();var e=this.bounds,d=e.height+(this.transparent?1:2)*this.padding,j=a.chartRect;b?(c.y=j.y,j.automatic&&j.setTop(j.y+d)):(c.y=j.y+j.height-e.height-this.padding,j.automatic&&(j.height-=d));0>j.height&&(j.height=0);c.x=0.5*(a.canvas.width-e.width)};this.tryDraw=function(b){if(this.visible&&this.text&&""!==this.text){this.calcRect(b);
var e=this.bounds,d=this.chart.ctx,j=d.beginParent;this.visual=j?d.beginParent():null;if(this._expand){var i=a.panel.format;c.x=""!==i.stroke.fill?i.stroke.size:0;c.y=b?c.x:a.canvas.height-(i.shadow.visible?i.shadow.height:0)-c.x-e.height;e.width=a.canvas.width-(i.shadow.visible?i.shadow.width:0)-2*c.x;var k=this.format;k.round.x=i.round.x;k.round.y=i.round.y;k.round.corners=[b,b,!b,!b];k.stroke.fill="";this.transparent=!1}e.x=c.x;e.y=c.y;this.doDraw();j&&d.endParent()}}}function U(a){var d=this.format=
new Tee.Format(a);d.round.x=12;d.round.y=12;d.stroke.size=3;d.gradient.visible=!0;d.gradient.direction="bottomtop";d.shadow.visible=!0;d.stroke.fill="#606060";this.transparent=!!a.__webgl;this.margins=new K;this.clear=function(){var b=a.bounds;a.ctx.clearRect(b.x,b.y,b.width,b.height)};this.draw=function(){if(this.transparent||a.__webgl)this.clear();else{var b=a.chartRect,e=d.shadow;e.visible&&(b.width-=0.5*Math.abs(e.width)+2,b.height-=0.5*Math.abs(e.height)+2,0>e.width&&(b.x-=e.width),0>e.height&&
(b.y-=e.height));var c=0;""!==d.stroke.fill&&(c=d.stroke.size,1<c&&(c*=0.5,b.x+=c,b.y+=c,b.width-=2*c,b.height-=2*c));(e.visible||0<d.round.x||0<d.round.y)&&this.clear();d.rectangle(b);0<c&&(b.x+=c,b.y+=c,b.width-=2*c,b.height-=2*c)}}}function F(a){var d=this.format=new Tee.Format(a);d.fill="#E6E6E6";d.stroke.fill="black";d.z=0;d.depth=0;this.visible=!0;this.bounds=new n;this.size=0;this.draw=function(){d.cube(this.bounds);d.draw(a.ctx,null,this.bounds)}}function x(a,d,b){function e(b){this.chart=
b;this.stroke=new B(b);this.stroke.cap="butt";this.visible=!0;this.length=4}function c(b){Tee.Annotation.call(this,b);this.padding=4;this.transparent=!0;this.format.font.textAlign="center"}function f(b,a){var e=0,f,c=a.split(" "),d;for(d=0;d<c.length;d++)f=b.textWidth(c[d]),f>e&&(e=f);return e}function h(b){return isFinite(b)?10<=b?10*h(0.1*b):1>b?0.1*h(10*b):2>b?2:5>b?5:10:1}this.chart=a;this.visible=!0;this.inverted=!1;this.horizontal=d;this.otherSide=b;this.bounds=new n;this.position=0;this.format=
new Tee.Format(a);this.format.stroke.size=2;this.format.depth=0.2;this.custom=!1;this.z=b?1:0;this.labels=new function(b,a){this.chart=b;this.format=new Tee.Format(b);this.decimals=2;this.padding=4;this.separation=10;this.visible=!0;this.rotation=0;this.alternate=!1;this.maxWidth=0;this.wordWrap="no";this.labelStyle="auto";this.dateFormat="shortDate";this.checkStyle=function(){var b=this.labelStyle,e=a.firstSeries;this._text=null;if("auto"==b)0<e.data.labels.length&&(e.associatedToAxis(a)&&a.horizontal==
e.notmandatory.horizontal)&&(this._text=e);else if("mark"==b||"text"==b)this._text=e};this.getLabel=function(e){var f=e|0,c;if(this._text&&f==e){if(c=this._text.data,c.x&&(f=c.x.indexOf(f)),c=c.labels[f],!c){var d=b.series.items,g,h;for(g=0;(h=d[g++])&&(!(h!=this._text&&h.visible&&h.associatedToAxis(a))||!(c=h.data.labels[f])););void 0===c&&(c="")}}else c=a.dateTime&&Date.prototype.format?(new Date(e)).format(this.dateFormat):this.valueFormat?e.toLocaleString():e.toFixed(f==e?0:this.decimals);this.ongetlabel&&
(c=this.ongetlabel(e,c),this.format.font.prepare());return""+c};this.width=function(b){return this.format.textWidth(this.getLabel(b))}}(a,this);var g=this.labels.format.font;this.scroll=function(b){this.automatic=!1;this.inverted&&(b=-b);this.minimum+=b;this.maximum+=b};d?(g.textAlign="center",g.baseLine=b?"bottom":"top"):(g.textAlign=b?"left":"right",g.baseLine="middle");this.grid=new function(b){this.chart=b;b=this.format=new Tee.Format(b);b.stroke.fill="silver";b.stroke.cap="butt";b.fill="";this.visible=
!0;this.lineDash=!1}(a);this.ticks=new e(a);this.innerTicks=new e(a);this.innerTicks.visible=!1;g=this.minorTicks=new e(a);g.visible=!1;g.length=2;g.count=3;c.prototype=new Tee.Annotation;this.title=new c(a);this.automatic=!0;this.increment=this.maximum=this.minimum=0;this.log=!1;this.start=this.endPos=this.startPos=0;this.end=100;this.increm=this.scale=this.axisSize=0;this.minmaxLabelWidth=function(){var b=this.labels,a=b._text,e=0,c,d;if(null!==a){d="auto"==b.wordWrap||"yes"==b.wordWrap;for(var h=
0,g=a.data.labels.length;h<g;h++)c=a.data.labels[h],this.ongetlabel&&(c=this.ongetlabel(h,c)),c&&(e=Math.max(e,d?f(b.format,c):b.format.textWidth(c)))}else e=this.roundMin(),a=this.maximum,e=Math.max(b.width(e),b.width(0.5*(e+a))),e=Math.max(e,b.width(1E-7)),e=Math.max(e,b.width(a));return e};this.checkMinMax=function(){var b=this.chart.series,a=this.horizontal;this.automatic&&(this.minimum=a?b.minXValue(this):b.minYValue(this),this.maximum=a?b.maxXValue(this):b.maxYValue(this))};this.calcAxisScale=
function(){var b=this.maximum-this.minimum;0===b?b=1:this.log&&(b=Math.log(b));this.scale=this.axisSize/b};this.calcScale=function(){var b=this.labels,a;b.format.font.prepare();a=this.horizontal?this.minmaxLabelWidth():b.format.textHeight("Wj");b.alternate&&(a*=0.5);a*=1+0.02*b.separation;if(0===this.increment)if(this.maximum==this.minimum)b=1;else{b=this.axisSize/a;b:{a=b;var e,c,f;for(e=0;c=this.chart.series.items[e++];)if(c.visible&&c.sequential&&((f=c.yMandatory)&&this.horizontal||!f&&!this.horizontal)&&
c.associatedToAxis(this)&&c.count()<=a){a=!0;break b}a=!1}b=Math.abs(this.maximum-this.minimum)/(b+1);b=a?Math.max(1,b):h(b)}else b=this.increment;this.increm=b;0>=this.increm&&(this.increm=0.1)};this.hasAnySeries=function(){var b=this.chart.series.items,a,e;for(a=0;e=b[a++];)if(e.visible&&e.associatedToAxis(this))return b=this.horizontal,e.yMandatory&&(b=!b),this.dateTime=(b=b?e.data.values:e.data.x)&&0<b.length&&b[0]instanceof Date,e;return null};this.drawAxis=function(){var b=this.format,a=this.chart.ctx,
e=this.axisPos,c=this.startPos,f=this.endPos,h=20*b.depth;this.chart.aspect.view3d&&0<h?(e=d?{x:c,y:e-0.5*h,width:f-c,height:h}:{x:e-0.5*h,y:c,width:h,height:f-c},c=this.z,b.z=c-0.5*b.depth,b.cylinder(e,1,!d),b.draw(a,null,e),b.z=c):(a.z=this.z,a.beginPath(),d?(a.moveTo(c,e),a.lineTo(f,e)):(a.moveTo(e,c),a.lineTo(e,f)),b.stroke.prepare(),a.stroke())};this.drawGrids=function(){var a=this.chart.ctx,e,c=this.chart.chartRect,f=this.grid.format,h,g,p,u,s=this.roundMin();if(this.grid.centered)var t=0.5*
this.increm,s=s-t>=this.minimum?s-t:s+t;var t=this.chart.aspect,G=t.view3d,M=G&&t.orthogonal,m=G?1:0;a.beginPath();d?(g=this.bounds.y-m,u=b?c.getBottom()-1:c.y+1):(h=this.bounds.x+m,p=b?c.x+1:c.getRight()-1);var n,m=-1;if(""!==f.fill){var c=s,r=f.stroke.fill;for(f.stroke.fill="";c<=this.maximum;)e=this.calc(c),0===m%2&&(d?f.rectangle(n,u,e-n,g-u):f.rectangle(h,n,p-h,e-n)),n=e,c+=this.increm,m++;f.stroke.fill=r;a.fillStyle=""}c=s;M&&(d?(g-=t._orthoy,u-=t._orthoy):(h+=t._orthox,p+=t._orthox));s=f.stroke.dash&&
!a.setLineDash&&!a.mozCurrentTransform;for(a.z=G?this.chart.walls.back.format.z-0.01:0;c<=this.maximum;){m=this.calc(c);d?h=p=m:g=u=m;M&&(d?(h+=t._orthox,p+=t._orthox):(g-=t._orthoy,u-=t._orthoy));G&&(!this.otherSide&&a.lineZ)&&a.lineZ(h,g,0,a.z);if(s){n=a;var m=h,x=g,v=p,r=u;e=void 0;e=[10,5];n.save();var v=v-m,w=r-x,r=Math.sqrt(v*v+w*w),v=Math.atan2(w,v);n.translate(m,x);n.moveTo(0,0);n.rotate(v);x=e.length;v=0;w=!0;for(m=0;r>m;)m+=e[v++%x],m>r&&(m=r),w?n.lineTo(m,0):n.moveTo(m,0),w=!w;n.restore()}else a.moveTo(h,
g),a.lineTo(p,u);c+=this.increm}f.stroke.prepare();f.shadow.prepare(a);a.stroke()};this.roundMin=function(){if(0===this.increm)return this.minimum;var b=this.minimum/this.increm-this.minimum/this.increm%1;return this.increm*(0>=this.minimum?b:1+b)};this.drawTicks=function(a,e,c){var f=this.roundMin(),h=1+a.length,g=1;if(d&&b||!d&&!b)h=-h,g=-1;var h=h*e+this.axisPos,g=g*e+this.axisPos,p,u=1,s=0;0===c?p=this.increm:(u+=c,p=this.increm/u);var t=this.chart.ctx;for(t.beginPath();f<=this.maximum;){if(0===
c||0!==s++%u)e=this.calc(f),d?(t.moveTo(e,g),t.lineTo(e,h)):(t.moveTo(g,e),t.lineTo(h,e));f+=p}a.stroke.prepare();a.z=this.z;t.z=a.z;t.stroke()};this.drawTitle=function(){var b=this.labels,a,e;""!==this.title.text&&(d?(e=this.axisPos+this.title.padding,this.ticks.visible&&(e+=this.ticks.length),b.visible&&(b.format.font.prepare(),a=b.format.textHeight("Wj"),b.alternate&&(a*=2),e+=a),a=this.startPos+0.5*this.axisSize-0.5*this.title.bounds.width,this.title.position.x=a,this.title.position.y=e,this.title.forceDraw()):
(a=this.axisPos-this.title.bounds.height-this.title.padding,this.ticks.visible&&(a-=this.ticks.length),b.visible&&(e=b.maxWidth,b.alternate&&(e*=2),a-=e),e=this.startPos+0.5*(this.axisSize+this.title.bounds.width)+this.title.bounds.height,b=this.chart.ctx,b.save(),b.translate(a,e),b.rotate(-Math.PI/2),b.textAlign="center",this.title.position.x=0,this.title.position.y=0,this.title.forceDraw(),b.restore()))};this.drawLabel=function(b,a){var e=this.labels,c=e.getLabel(b);a.width=e.format.textWidth(c);
a.width>e.maxWidth&&(e.maxWidth=a.width);this.horizontal?a.x-=0.5*a.width:a.y+=0.5*a.height;if(0!==e.rotation){var f=this.chart.ctx;f.save();f.translate(a.x,a.y);f.rotate(-Math.PI*e.rotation/180);f.textAlign="right";a.x=-8;a.y=3}"right"==e.format.font.textAlign&&(a.x-=a.width);e.format.z=this.z*this.chart.walls.back.format.z;e.format.drawText(a,c);0!==e.rotation&&this.chart.ctx.restore()};this.drawLabels=function(){var b=this.roundMin(),a=new n,e=this.axisPos,c=this.labels;c.maxWidth=0;c.format.font.prepare();
var f=this.ticks.visible?this.ticks.length:0,f=f+c.padding;this.horizontal?this.otherSide?e-=f:e+=f:this.otherSide?e+=f:e-=f;f=e;a.height=c.format.textHeight("Wj");for(var d=(c=c.alternate)?this.horizontal?-a.height:this.minmaxLabelWidth():0,h;b<=this.maximum;)h=this.calc(b),this.horizontal?(a.x=h,a.y=e):(a.x=e,a.y=h-0.5*a.height),c&&(e=e==f?this.otherSide?f+d:f-d:f),this.drawLabel(b,a),b+=this.increm};this.calc=function(b){b!==b?b=0:this.log?(b-=this.minimum,b=0>=b?0:Math.log(b)*this.scale):b=(b-
this.minimum)*this.scale;return this.horizontal?this.inverted?this.endPos-b:this.startPos+b:this.inverted?this.startPos+b:this.endPos-b};this.fromPos=function(b){var a=this.horizontal;this.inverted&&(a=!a);return this.minimum+(a?b-this.startPos:this.endPos-b)/this.scale};this.fromSize=function(b){return b/this.scale};this.calcSize=function(b){return Math.abs(this.calc(b)-this.calc(0))};this.calcMinMax=function(b,a){this.automatic=!1;var e=this.fromPos(b),c=this.fromPos(a),f;e>c&&(f=e,e=c,c=f);this.minimum=
e;this.maximum=c};this.setMinMax=function(b,a){this.automatic=!1;this.minimum=b;this.maximum=a}}function V(a){this.chart=a;this.transparent=!1;var d=this.format=new Tee.Format(a);d.fill="white";d.round.x=8;d.round.y=8;d.font.baseLine="top";d.shadow.visible=!0;d.z=0;d.depth=0.05;this.title=new Tee.Annotation(a);this.title.transparent=!0;this.bounds=new n;this.position="right";this.visible=!0;this.inverted=!1;this.margin=this.padding=5;this.align=0;this.fontColor=!1;var b=this.dividing=new B(a);b.fill=
"";b.cap="butt";this.over=-1;this.symbol=new function(b){this.chart=b;var a=this.format=new Tee.Format(b),e=a.shadow;e.visible=!0;e.color="silver";e.width=2;e.height=2;a.depth=0.01;this.padding=this.height=this.width=8;this.style="rectangle";this.visible=!0;this.draw=function(e,c,f,d){var h=b.ctx,g;a:{if(e.hover.enabled){var i=b.legend.showValues();if(i&&e.over==c||!i&&0<=e.over){g=e.hover;break a}}g=null}var i=a.fill,j=a.stroke;a.fill=e.legendColor(c);h.z=-0.01;"rectangle"===this.style?(g&&(a.stroke=
g.stroke),this.chart.aspect.view3d?(e={x:f,y:d-0.5*this.height-1,width:this.width,height:this.height},i=a.z,c=h.z,a.z=h.z-a.depth,a.cube(e),a.draw(h,null,e),a.z=i,h.z=c):a.rectangle(f,d-0.5*this.height-1,this.width,this.height)):(h.beginPath(),h.moveTo(f,d),h.lineTo(f+this.width,d),g?g.stroke.prepare():a.stroke.prepare(a.fill),h.stroke());a.fill=i;a.stroke=j}}(a);this.itemHeight=10;this.innerOff=0;this.textStyle=this.legendStyle="auto";this.totalWidth=function(){var b=j+8,a=this.symbol;a.visible&&
(b+=a.width+a.padding);return b};var e=0;this._space=function(){return this.bounds.y+e+0.01*this.margin*a.bounds.height};this.availRows=function(){var b=this._space()+0.5*this.itemHeight;b||(b=0);return(a.bounds.getBottom()-b)/this.itemHeight|0};this.itemsCount=function(){var b=a.series,e=b.visibleCount(),c=a.bounds;if(0===e)return 0;var f=this.legendStyle;"values"===f&&0<e?e=b.firstVisible().legendCount():"auto"===f&&1<e||"series"===f||1==e&&(e=b.firstVisible().legendCount());this.isVertical()?(0.5+
e)*this.itemHeight>c.height-this._space()&&(e=this.availRows()):(this.rows=1,b=this.totalWidth(),f=this.calcPadding(c),f=c.width-2*f,e*b>f?(this.perRow=f/b|0,e>this.perRow&&(this.rows=1+(e/this.perRow|0),this.rows*this.itemHeight>c.height-this.bounds.y&&(this.rows=this.availRows(),e=this.rows*this.perRow))):this.perRow=e);return e};this.showValues=function(){var b=this.legendStyle;return"values"==b||"auto"==b&&1==a.series.visibleCount()};this.itemText=function(b,a){var e=b.legendText(a,this.textStyle,
!1,!0);return this.ongettext?this.ongettext(this,b,a,e):e};this.calcItemPos=function(b,a){var c=this.itemHeight,f=this.bounds;a.x=f.x;a.y=f.y+this.innerOff;this.isVertical()?(a.x+=f.width-6-this.innerOff,a.y+=0.4*c+b*c+e):(a.x+=this.innerOff+(1+b%this.perRow)*this.totalWidth(),a.y+=c*((b/this.perRow|0)+0.25))};this.calcItemRect=function(b,a){var c=this.itemHeight,f=this.bounds;a.height=c;a.x=f.x;a.y=f.y;this.isVertical()?(a.width=f.width,a.y+=0.4*c+b*c+e):(a.width=this.totalWidth(),a.x+=this.innerOff+
b%this.perRow*a.width,a.y+=c*((b/this.perRow|0)+0.25))};var c=new n;this.mousemove=function(b){var a=this.over;if(this.bounds.contains(b))for(var e=this.itemsCount(),f=0;f<e;f++){if(this.calcItemRect(f,c),c.contains(b)){a=f;break}}else a=-1;if(a!=this.over){if(this.onhover)this.onhover(this.over,a);this.over=a;var d=this.chart;window.requestAnimFrame(function(){d.draw()})}};this.drawSymbol=function(b,a,e){var c=this.symbol;c.draw(b,a,e.x-j-c.width-c.padding,e.y+0.4*this.itemHeight)};var f={x:0,y:0},
h=new n,g;this.drawItem=function(b,a,e,c){var p=this.isVertical();this.calcItemPos(e,f);h.x=f.x;h.y=f.y;p?h.y-=this.chart.isMozilla?0:2:this.chart.isMozilla?h.y++:h.y--;var u=d.font.fill;this.over==e?d.font.fill="red":this.fontColor&&(d.font.fill=this.showValues()?a.legendColor(e):a.format.fill);var s=this.chart.ctx;if(c)d.font.textAlign="start",h.x-=i[0],s.textAlign=d.font.textAlign,d.drawText(h,b);else if(b instanceof Array||(b=[b]),p){for(var c=b.length,p=h.width,t=d.textWidth(" ");c--;)d.font.textAlign=
g[c]?"start":"end",h.x-=i[c],s.textAlign=d.font.textAlign,d.drawText(h,b[c]),h.width-=i[c]+t;h.width=p}else d.font.textAlign="start",h.x-=j,s.textAlign=d.font.textAlign,d.drawText(h,b.join(" "));d.font.fill=u;b=!a.isColorEach||this.showValues();this.symbol.visible&&b&&this.drawSymbol(a,e,f);0<e&&""!==this.dividing.fill&&(a=this.bounds,s.beginPath(),this.isVertical()?(s.moveTo(a.x,h.y-2),s.lineTo(a.getRight(),h.y-2)):(e=h.x-j-4,b=this.symbol,b.visible&&(e-=b.width+b.padding),s.moveTo(e,a.y),s.lineTo(e,
a.getBottom())),this.dividing.prepare(),s.stroke())};this.drawSeries=function(b,e){var c=a.series.items[b];return c.visible?(this.drawItem(c.titleText(b),c,e,!0),!0):!1};this.draw=function(){var b=this.itemsCount(),c,f;c=this.title;var i=a.ctx,p,u=this.format.transparency,s=this.isVertical();if(0<b){var t=i.beginParent;this.visual=t?i.beginParent():null;this.transparent||(d.cube(this.bounds),d.draw(i,null,this.bounds));0<u&&(p=i.globalAlpha,i.globalAlpha=(1-u)*p);s&&0<e&&(c.bounds.x=this.bounds.x-
4,c.bounds.y=this.bounds.y,c.doDraw());d.font.prepare();h.width=j;h.height=this.itemHeight;if(this.showValues()){s=a.series.firstVisible();f=0;c=b;switch(this.textStyle){case "auto":case "percentlabel":case "valuelabel":g=[!1,!0];break;case "labelpercent":case "labelvalue":g=[!0,!1];break;case "label":g=[!0];break;default:g=[!1]}if(this.inverted)for(;c--;)this.drawItem(this.itemText(s,c),s,f++);else for(f=0;f<c;f++)this.drawItem(this.itemText(s,f),s,f)}else if(c=a.series.count(),s&&(c=Math.min(c,
this.availRows())),b=0,g=[!0],this.inverted)for(;c--;)this.drawSeries(c,b)&&b++;else for(f=0;f<c;f++)this.drawSeries(f,b)&&b++;0<u&&(i.globalAlpha=p);t&&i.endParent()}};var j,i;this.calcWidths=function(){var b,e,c,f,h=a.series;j=0;i=[0,0];if(this.showValues()){b=h.firstVisible();f=this.itemsCount();for(e=0;e<f;e++)h=this.itemText(b,e),h instanceof Array||(h=[h]),0<h.length&&(c=d.textWidth(h[0]),c>i[0]&&(i[0]=c),1<h.length&&(c=d.textWidth(h[1]),c>i[1]&&(i[1]=c)))}else{f=h.count();for(e=0;e<f;e++)b=
h.items[e],b.visible&&(c=d.textWidth(b.titleText(e)),c>i[0]&&(i[0]=c))}j=i[0]+i[1]};this.calcPadding=function(b){return 0.01*this.padding*(this.isVertical()?b.width:b.height)};this.isVertical=function(){var b=this.position;return"right"===b||"left"===b};this.calcrect=function(){var b=0,c=this.title,f=a.chartRect,h=this.align,g=this.bounds,i=this.isVertical();c.visible&&""!==c.text?(c.resize(),e=c.bounds.height,b=c.bounds.width):e=0;i?g.y=0===h?f.y:0.01*a.bounds.height*h:g.x=0===h?f.x:0.01*a.bounds.width*
h;d.font.prepare();this.itemHeight=d.textHeight("Wj");this.calcWidths();var h=this.calcPadding(f),s=this.itemsCount();i?(i=this.symbol.visible?this.symbol.width+this.symbol.padding:0,g.width=Math.max(b,12+j+i),g.height=(0.5+s)*this.itemHeight+e,g.width-6>b&&(c.bounds.width=g.width-6)):(g.width=h+this.perRow*this.totalWidth(),g.x+=0.5*(f.width-g.width),g.height=this.itemHeight*(this.rows+0.25));""!==d.stroke.fill&&(i=+d.stroke.size,1<i&&(g.width+=i,g.height+=i,this.innerOff=0.5*i));0!==s&&("right"===
this.position?(g.x=f.getRight()-g.width-0.01*this.margin*g.width,f.automatic&&f.setRight(Math.max(f.x,g.x-h))):"left"===this.position?(g.x=f.x,f.automatic&&f.setLeft(g.x+g.width+h)):"top"===this.position?(g.y=f.y+h,f.automatic&&f.setTop(g.getBottom()+h)):(g.y=f.getBottom()-g.height-h,f.automatic&&f.setBottom(g.y-h)))}}function N(a,d){Tee.Annotation.call(this,d);this.series=a;var b=this.arrow=new Tee.Format(d);b.length=10;b.underline=!1;b.z=0.5;b.depth=0.1;this.style="auto";this.drawEvery=1;this.visible=
!1;this.format.z=0.5;this.setChart=function(a){this.chart=a;this.format.setChart(a);b.setChart(a)};this.drawPolar=function(a,c,f,h){var d=this.series.markText(h),h=a.x+Math.cos(f)*c,j=a.y+Math.sin(f)*c,i=this.chart.ctx;this.text=d;this.resize();var d=this.bounds,k,l=this.position,c=c+b.length;k=a.x+Math.cos(f)*c;c=a.y+Math.sin(f)*c;0>k-d.width&&(k-=k-d.width-4);l.x=Math.abs(k-a.x)<d.width?k-0.5*d.width:k<a.x?k-d.width:k;l.y=Math.abs(c-a.y)<d.height?c-0.5*d.height:c<a.y?c-d.height:c;i.beginPath();
i.moveTo(h,j);i.lineTo(k,c);if(b.underline&&(c<=l.y||c>=l.y+d.height))i.moveTo(l.x,c),i.lineTo(l.x+d.width,c);b.stroke.prepare();i.stroke();this.draw()};this.canDraw=function(a,c,f,d){if((f=this.series.markText(f))&&""!==f&&(this.showZero||"0"!==f)){this.text=f;this.resize();var f=d?-1:1,g=this.bounds;this.series.yMandatory?(g.x=a-0.5*g.width,g.y=c-f*(b.length+(d?0:g.height))):(g.x=a+f*b.length,d&&(g.x-=g.width),g.y=c-0.5*g.height);this.position.x=g.x;this.position.y=g.y;return!0}return!1};this.drawMark=
function(a,c,f,d){if(this.canDraw(a,c,f,d)){this.draw();var f=this.bounds,g=this.series.yMandatory,j=d?f.y:f.getBottom(),i=this.chart.ctx,k=this.chart.aspect.view3d;if(g){if(k){a={x:a-3,y:j,width:6,height:c-j};b.z=this.format.z-0.5*b.depth;b.cylinder(a,1,!0);b.draw(this.chart.ctx,null,a);return}i.beginPath();i.moveTo(a,j);i.lineTo(a,c);b.underline&&(i.moveTo(f.x,j),i.lineTo(f.x+f.width,j))}else c=f.y+0.5*f.height,i.beginPath(),i.moveTo(a,c),d&&(f.x+=f.width),i.lineTo(f.x,c),b.underline&&(i.moveTo(f.x,
f.y+f.height),i.lineTo(f.x+(d?-f.width:f.width),f.y+f.height));b.stroke.prepare();i.stroke()}}}function O(a){for(var d=0,b=a.length;b--;)d+=0<a[b]?a[b]:-a[b];return d}function J(a){function d(b){return b.visible&&b.firstSeries?(b=b.format.stroke,""===b.fill?0:0.5*b.size):0}this.chart=a;this.items=[];this.count=function(){return this.items.length};this.clicked=function(b){var a=!1;this.each(function(c){if(c.visible&&c.onclick){var f=c.clicked(b);-1!=f&&(a=c.onclick(c,f,b.x,b.y))}});return a};this.mousedown=
function(b){for(var a=0,c,f=!1;c=this.items[a++];)c.visible&&c.mousedown(b)&&(f=!0);return f};this.mousemove=function(b){for(var a=0,c;c=this.items[a++];)c.visible&&c.mousemove(b)};this.mouseout=function(){this.each(function(b){b.visible&&b.mouseout()})};this.visibleCount=function(b,a,c){for(var f=0,d=this.items,g=d.length,j;g--,j=d[g];)if(j.visible&&(!a||j instanceof a))c&&j==b&&(c.index=f),f++;c&&(c.total=f,c.index=f-1-c.index);return f};this.beforeDraw=function(){this.each(function(b){b.useAxes&&
b.recalcAxes();b.calcColorEach()})};this.anyUsesAxes=function(){for(var b=this.items.length,a;b--;)if(a=this.items[b],a.visible&&a.useAxes)return!0;return!1};this.firstVisible=function(){for(var b=0,a;a=this.items[b++];)if(a.visible)return a;return null};this.vertMargins=function(){var b,a=this.items,c=a.length,f,d;if(0<c){b={x:0,y:0};f={x:0,y:0};a[0].vertMargins(b);for(d=1;d<c;d++)f.x=f.y=0,a[d].vertMargins(f),f.x>b.x&&(b.x=f.x),f.y>b.y&&(b.y=f.y)}return b};this.horizMargins=function(){var b,a=this.items,
c=a.length,f,d;if(0<c){b={x:0,y:0};f={x:0,y:0};a[0].horizMargins(b);for(d=1;d<c;d++)f.x=f.y=0,a[d].horizMargins(f),f.x>b.x&&(b.x=f.x),f.y>b.y&&(b.y=f.y)}return b};this.minXValue=function(b){var a=Infinity,c;this.eachAxis(b,function(b){c=b.minXValue();c<a&&(a=c)});return a};this.minYValue=function(b){var a=Infinity,c;this.eachAxis(b,function(b){c=b.minYValue();c<a&&(a=c)});return a};this.maxXValue=function(b){var a=-Infinity,c;this.eachAxis(b,function(b){c=b.maxXValue();c>a&&(a=c)});return a};this.maxYValue=
function(b){var a=-Infinity,c;this.eachAxis(b,function(b){c=b.maxYValue();c>a&&(a=c)});return a};this.draw=function(){var b=this.items.length,a=this.chart,c=a.ctx,f=a.aspect,h,g;if(0<b){for(h=0;h<b;h++)g=this.items[h],g.visible&&g.beforeDraw&&g.beforeDraw();var j=f.clip&&this.anyUsesAxes(),i=a.axes;if(j){var a=a.chartRect,k=d(i.left),l=d(i.top),i={x:a.x+k,y:a.y+l,width:a.width-d(i.right),height:a.height-d(i.bottom)};f.clipRect(i)}try{for(h=0;h<b;h++)if(g=this.items[h],g.visible){var q=c.globalAlpha;
c.globalAlpha=1-g.format.transparency;g.transform&&(c.save(),g.transform());g.draw();if(g.ondraw)g.ondraw(g);g.transform&&c.restore();c.globalAlpha=q}}finally{j&&c.restore()}for(h=0;h<b;h++)g=this.items[h],g.visible&&g.marks.visible&&(g.transform&&(c.save(),g.transform()),g.drawMarks(),g.transform&&c.restore())}}}function W(a){this.chart=a;this.visible=!0;this.transparency=0;this.left=new x(a,!1,!1);this.top=new x(a,!0,!0);this.right=new x(a,!1,!0);this.bottom=new x(a,!0,!1);this.items=[this.left,
this.top,this.right,this.bottom];this.each=function(a){for(var b=0,e;e=this.items[b++];)a.call(e)};this.add=function(d,b){var e=new x(a,d,b);e.custom=!0;this.items.push(e);return e}}"undefined"!==typeof exports&&(exports.Tee=Tee);"undefined"!==typeof window&&(window.requestAnimFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60,(new Date).getTime())});
var v;try{Object.defineProperty({},"x",{}),v=Object.defineProperty}catch(X){}"indexOf"in Array.prototype||(Array.prototype.indexOf=function(a,d){void 0===d&&(d=0);0>d&&(d+=this.length);0>d&&(d=0);for(var b=this.length;d<b;d++)if(d in this&&this[d]===a)return d;return-1});n.prototype.set=function(a,d,b,e){this.x=a;this.y=d;this.width=b;this.height=e};n.prototype.setFrom=function(a){this.x=a.x;this.y=a.y;this.width=a.width;this.height=a.height};n.prototype.getRight=function(){return this.x+this.width};
n.prototype.getBottom=function(){return this.y+this.height};n.prototype.setTop=function(a){this.height-=a-this.y;this.y=a};n.prototype.setBottom=function(a){this.height=a-this.y};n.prototype.setLeft=function(a){this.width-=a-this.x;this.x=a};n.prototype.setRight=function(a){this.width=a-this.x};n.prototype.contains=function(a){return a.x>=this.x&&a.x<=this.x+this.width&&a.y>=this.y&&a.y<=this.y+this.height};n.prototype.offset=function(a,d){this.x+=a;this.y+=d};Tee.Tool=function(a){this.chart=a;this.active=
!0};Tee.Animation=function(a,d){Tee.Tool.call(this,a);this.active=!0;this.mode="linear";this.duration=500;this.items=[];this.running=this.loop=!1;this.onstop=this.onstart=null;a&&(a instanceof Tee.Chart?this.chart=a:a instanceof Tee.Animation&&(this.chart=a.chart,a.items.push(this)));var b=null;this._dostart=function(){this.init=(new Date).getTime();b.start();for(var a=0,c;c=b.items[a++];)c.active&&(c.chart=b.chart,c.start());b.chart.draw();requestAnimFrame(this.step,this)};this.animate=function(a){this.running||
(this.running=!0,a&&(this.chart=a),b=this,this._dostart())};this.start=function(){if(this.onstart)this.onstart()};this.stop=function(){if(this.onstop)this.onstop()};this.doStep=function(b){d&&d(b)};this.step=function(){var a,c;a=((new Date).getTime()-b.init)/b.duration;var f="linear"==b.mode?a:Math.pow(2,10*(a-1));if(0<=f&&1>f){b.doStep(f);for(a=0;c=b.items[a++];)c.active&&(c.chart=b.chart,c.doStep(f));b.chart.draw();requestAnimFrame(b.step,b)}else{b.stop();for(a=0;c=b.items[a++];)c.active&&(c.chart=
b.chart,c.stop());if(b.onstop)b.onstop(b);b.loop?b._dostart():(b.running=!1,b.chart.draw())}}};Tee.Animation.prototype=new Tee.Tool;Tee.Tool.prototype.mousedown=function(){};Tee.Tool.prototype.mousemove=function(){};Tee.Tool.prototype.mouseout=function(){};Tee.Tool.prototype.clicked=function(){return!1};Tee.Tool.prototype.draw=function(){};z.prototype.setEndColor=function(a){if(a&&""!==a)for(var d=1,b=this.colors.length;d<b;d++)this.colors[d]=a};A.prototype.set=function(a){this.visible=a.visible;
this.color=a.color;this.blur=a.blur;this.width=a.width;this.height=a.height};C.prototype.getSize=function(){var a=this.style.split(" "),d,b;for(d=0;d<a.length;d++)if(b=parseFloat(a[d]))return b;return 20};C.prototype.setSize=function(a){var d="",b=this.style.split(" "),e;for(e=0;e<b.length;e++)parseFloat(b[e])?d+=a.toString()+"px ":d+=b[e]+" ";this.style=d};C.prototype.prepare=function(){var a=this.chart.ctx;a.textAlign=this.textAlign;a.textBaseline=this.baseLine;this._sh&&this._sh.prepare(a);a.font!=
this.style&&(a.font=this.style)};C.prototype.setChart=function(a){this.chart=a;this._g&&(this._g.chart=a);this._sh&&(this._sh.chart=a);this._s&&this._s.setChart(a)};Tee.Format=function(a){this.chart=a;this.gradient=new z(a);this.fill="rgb(200,200,200)";this.stroke=new B(a);this.round={x:0,y:0};this.transparency=0;this.font=new C(a);this._img=null;v?v(this,"image",{get:function(){this._img||(this._img=new L(this.chart));return this._img}}):this._img=this.image=new L(a);this.shadow=new A(a);this.roundRect=
function(b,a,c,f,d){if(b.roundRect)b.roundRect(a,c,f,d,this.round.x,this.round.y);else{var g=a+f,j=c+d,i=this.round.x,k=this.round.y,l=this.round.corners;0>d&&(c=j,j=c-d);0>f&&(a=g,g=a-f);2*i>f&&(i=0.5*f);2*k>d&&(k=0.5*d);!l||l[0]?b.moveTo(a+i,c):b.moveTo(a,c);!l||l[1]?(b.lineTo(g-i,c),b.quadraticCurveTo(g,c,g,c+k)):b.lineTo(g,c);!l||l[2]?(b.lineTo(g,j-k),b.quadraticCurveTo(g,j,g-i,j)):b.lineTo(g,j);!l||l[3]?(b.lineTo(a+i,j),b.quadraticCurveTo(a,j,a,j-k)):b.lineTo(a,j);!l||l[0]?(b.lineTo(a,c+k),b.quadraticCurveTo(a,
c,a+i,c)):b.lineTo(a,c);b.closePath()}};this.textHeight=function(){return 1.3*this.font.getSize()};this.textWidth=function(b){return this.chart.ctx.measureText(b).width};this.draw=function(b,a,c,f,d,g){var j=this._img,i;"object"===typeof c&&(f=c.y,d=c.width,g=c.height,c=c.x);0<this.transparency&&(i=b.globalAlpha,b.globalAlpha=(1-this.transparency)*i);this.shadow.prepare(b);j&&j.visible&&""!==j.url?(b.save(),b.clip(),a?(a=a(),j.tryDraw(a.x,a.y,a.width,a.height)):j.tryDraw(c,f,d,g),b.restore()):this.gradient.visible?
(b.fillStyle=a?this.gradient.create(a()):this.gradient.rect(c,f,d,g),b.fill()):""!==this.fill&&(b.fillStyle=this.fill,b.fill());""!==this.stroke.fill&&(this.stroke.prepare(),b.stroke());0<this.transparency&&(b.globalAlpha=i)};this.drawText=function(b,a){function c(b){d.fillText(b,i,k);g&&""!==g.fill&&(g.prepare(),d.strokeText(b,i,k))}var f=this.font._g,d=this.chart.ctx,g=this.font._s,j=this.font.textAlign,i=b.x,k=b.y;d.fillStyle=f&&f.visible&&b?f.create(b):this.font.fill;if("center"==j)i+=0.5*b.width;
else if("right"==j||"end"==j)i+=b.width;f=a.split("\n");j=f.length;if(1<j)for(var l=this.textHeight(f[0]),q=0;q<j;q++)c(f[q]),k+=l;else c(a)};this.rectangle=function(b,a,c,f){1>this.transparency&&("object"===typeof b?this.rectangle(b.x,b.y,b.width,b.height):(this.rectPath(b,a,c,f),this.draw(this.chart.ctx,null,b,a,c,f)))};this.polygonBounds=function(b,a){var c=0,f=0,d=0,g=0,j=b.length,i,k;if(0<j){c=d=b[0].x;f=g=b[0].y;for(k=1;k<j;k++)i=b[k].x,i<c?c=i:i>d&&(d=i),i=b[k].y,i<f?f=i:i>g&&(g=i)}a.x=c;a.y=
f;a.width=d-c;a.height=g-f};var d=new n;this.polygon=function(b){var a=this.chart.ctx,c=b.length,f;a.beginPath();a.moveTo(b[0].x,b[0].y);for(f=1;f<c;f++)a.lineTo(b[f].x,b[f].y);a.closePath();var h=this;this.draw(a,function(){h.polygonBounds(b,d);return d})}};Tee.Format.prototype.ellipsePath=function(a,d,b,e,c){this.chart.__webgl?(a.z=this.z,a.depth=this.depth,a.ellipsePath(d,b,e,c)):(a.save(),a.translate(d,b),a.scale(0.5*e,0.5*c),a.beginPath(),a.arc(0,0,1,0,2*Math.PI,!1),a.restore())};Tee.Format.prototype.ellipse=
function(a,d,b,e){var c=this.chart.ctx;this.ellipsePath(c,a,d,b,e);this.draw(c,null,a-0.5*b,d-0.5*e,b,e)};Tee.Format.prototype.sphere=function(a,d,b,e){if(this.chart.__webgl){var c=this.chart.ctx;c.depth=this.depth;c.z=this.z;this.gradient.visible&&(c.fillStyle=this.gradient.colors[this.gradient.colors.length-1]);c.sphere(a,d,b,e)}else this.ellipse(a,d,b,e)};Tee.Format.prototype.cylinder=function(a,d,b,e){if(this.chart.__webgl){var c=this.chart.ctx;c.depth=this.depth;c.z=this.z;c.image=this.image;
c.cylinder(a,d,b,e)}else 1==d?this.cube(a):(d=a.width,e=a.height,b?this.polygon([new m(a.x+0.5*d,a.y),new m(a.x,a.y+e),new m(a.x+d,a.y+e)]):this.polygon([new m(a.x+d,a.y+0.5*e),new m(a.x,a.y),new m(a.x,a.y+e)]))};Tee.Format.prototype.cube=function(a){var d=this.chart.aspect,b=d.view3d,e,c,f,h=0,g=0;if(b){if(this.chart.__webgl){b=this.chart.ctx;b.depth=this.depth;b.z=this.z;b.cube(a,this.round.x);return}e=this.z;var j=this.depth,h=e*d._orthox,g=-e*d._orthoy;e=a.x+a.width;c=a.y+a.height;var i=j*d._orthox,
d=-j*d._orthoy;f=this.shadow.visible;this.shadow.visible=!1;var k=e+i,l=a.y+d;0<j&&(this.polygon([{x:e,y:a.y},{x:k,y:l},{x:k,y:c+d},{x:e,y:c}]),0<a.width&&this.polygon([{x:a.x,y:a.y},{x:a.x+i,y:l},{x:k,y:l},{x:e,y:a.y}]))}this.rectPath(a.x+h,a.y+g,a.width,a.height);b&&(this.shadow.visible=f)};Tee.Format.prototype.rectPath=function(a,d,b,e){var c=this.chart.ctx;c.beginPath();0<this.round.x&&0<this.round.y?this.roundRect(c,a,d,b,e):c.rect(a,d,b,e)};Tee.Format.prototype.setChart=function(a){this.chart=
a;this.shadow.chart=a;this.gradient.chart=a;this.font.setChart(a);this._img&&(this._img.chart=a);this.stroke.setChart(a)};Tee.Annotation=function(a,d,b,e){Tee.Tool.call(this,a);this.position=new m(b||10,e||10);var c=this.margins=new K;this.items=[];var f=this.bounds=new n;this.visible=!0;this.transparent=!1;this.text=d||"";var h=this.format=new Tee.Format(a);h.font.textAlign="center";h.font.baseLine="top";h.fill="beige";h.round={x:4,y:4};h.stroke.fill="silver";h.shadow.visible=!0;h.depth=0.05;h.z=
0.5;var g,j,i;this.moveTo=function(b,a){this.position.x=b;this.position.y=a;this.resize()};this.resize=function(){if(this.text){h.font.prepare();this.rows=this.text.split("\n");g=h.textHeight(this.text);var b=this.rows.length;j=g*b+c.top;var a,e=j+c.bottom;if(1<b)for(a=0;b--;)a=Math.max(a,h.textWidth(this.rows[b]+"W"));else a=h.textWidth(this.text+"W");a+=c.left+c.right;var b=this.position,d=b.y+j,i,u;for(i=0;u=this.items[i++];){var s=u.bounds;u.resize();e+=s.height;a=Math.max(a,s.width);s.x=b.x;
s.y=d;d+=s.height}for(i=0;u=this.items[i++];)u.bounds.width=a-c.right;f.set(b.x,b.y,a,e)}};this.add=function(b){b=new Tee.Annotation(this.chart,b);this.items.push(b);b.transparent=!0;return b};this.doDraw=function(){if(""!==this.text){if(this.transparent)this.chart.ctx.z=h.z;else if(this.chart.aspect.view3d&&0<this.format.depth){var b=h.z;h.z-=0.5*this.format.depth;h.cube(f);h.draw(this.chart.ctx,null,f);h.z=b}else this.chart.ctx.z=h.z,h.rectangle(f);var a,b=this.format.transparency,e=this.chart?
this.chart.ctx:null;0<b&&(a=e.globalAlpha,e.globalAlpha=(1-b)*a);h.font.prepare();f.y+=c.top+0.1*g;f.x+=c.left;var d=f.width;f.width-=c.right;h.drawText(f,this.text);f.x=this.position.x;f.y=this.position.y;f.width=d;0<b&&(e.globalAlpha=a)}for(a=0;b=this.items[a++];)b.doDraw()};this.clicked=function(b){return this.visible&&f.contains(b)};this.doMouseMove=function(b){(this.mouseinside=this.clicked(b))?(this.cursor&&(this.chart.newCursor=this.cursor),this.wasinside||(i=new Q(250,f,h))):this.wasinside&&
(i.restore(),this.chart.draw());this.wasinside=this.mouseinside};this.mousemove=function(b){this.cursor&&"default"!=this.cursor&&this.doMouseMove(b)};this.forceDraw=function(){this.resize();this.doDraw()};this.setChart=function(b){this.chart=b;this.format.setChart(b)}};Tee.Annotation.prototype=new Tee.Tool;Tee.Annotation.prototype.draw=function(){this.visible&&this.forceDraw()};Tee.DragTool=function(a){Tee.Tool.call(this,a);this.series=null;var d=this.target={series:null,index:-1};this.clicked=function(){d.series=
null;d.index=-1};var b=new m(0,0);this.mousedown=function(a){var c=this.chart.series.items,f=c.length;this.chart.calcMouse(a,b);d.series=null;d.index=-1;if(this.series&&this.series.visible)d.index=this.series.clicked(b),-1!=d.index&&(d.series=this.series);else for(a=0;a<f;a++)if(c[a].visible&&(d.index=c[a].clicked(b),-1!=d.index)){d.series=c[a];break}return-1!=d.index};this.mousemove=function(b){if(-1!=d.index){var a=d.series,b=a.mandatoryAxis.fromPos(a.yMandatory?b.y:b.x);this.onchanging&&(b=this.onchanging(this,
b));a.data.values[d.index]=b;if(this.onchanged)this.onchanged(this,b);this.chart.draw()}}};Tee.DragTool.prototype=new Tee.Tool;Tee.CursorTool=function(a){Tee.Tool.call(this,a);this.direction="both";this.size=new m(0,0);this.followMouse=!0;this.dragging=-1;this.format=new Tee.Format(a);this.horizAxis=a?a.axes.bottom:null;this.vertAxis=a?a.axes.left:null;var d,b=new n;this.over=function(a){var c=-1;if(b.contains(a)){var f=3>Math.abs(d.x-a.x),a=3>Math.abs(d.y-a.y),e=this.direction;if("both"==e&&f&&a)c=
0;else if(f&&("both"==e||"vertical"==e))c=1;else if(a&&("both"==e||"horizontal"==e))c=2}return c};this.calcRect=function(){var c=a.chartRect,f=this.horizAxis,e=this.vertAxis;b.x=f?f.startPos:c.x;b.width=f?f.endPos-b.x:c.width;b.y=e?e.startPos:c.y;b.height=e?e.endPos-b.y:c.height};var e=new m(0,0);this.mousedown=function(b){this.chart.calcMouse(b,e);this.dragging=this.followMouse?-1:this.over(e);return-1<this.dragging};this.clicked=function(){this.dragging=-1};this.mousemove=function(e){var g=this.dragging,
j=this.followMouse;if(j||-1<g)if(d||(d=new m),d.x!=e.x||d.y!=e.y)if(this.calcRect(),b.contains(e)){if(j||0===g||1===g)d.x=e.x;if(j||0===g||2===g)d.y=e.y;"full"==this.render?this.chart.draw():(c&&("copy"==this.render?this.chart.ctx.drawImage(c,0,0):(g=a.bounds,f.clearRect(g.x,g.y,g.width,g.height))),this.dodraw("copy"==this.render?this.chart.ctx:f));if(this.onchange)this.onchange(e);return}e=this.over(e);this.chart.newCursor=d&&-1<e?0===e?"move":1===e?"e-resize":"n-resize":"default"};this.render="copy";
var c,f;this.setRender=function(b){this.render=b;c&&(this.resetCopy(),this.chart.draw())};this.resetCopy=function(){var b=this.chart.canvas;"layer"==this.render?(c.style.position="absolute",b.parentNode.appendChild(c),c.setAttribute("left",b.offsetLeft+"px"),c.setAttribute("top",b.offsetTop+"px"),c.style.left=b.offsetLeft,c.style.top=b.offsetTop,c.style.zIndex=10,c.style.pointerEvents="none"):c.parentNode&&c.parentNode.removeChild(c)};this.draw=function(){"full"==this.render?this.dodraw(this.chart.ctx):
(c||(c=this.chart.canvas.cloneNode(),this.resetCopy(),f=c.getContext("2d")),"copy"==this.render?(f.drawImage(a.canvas,0,0),this.dodraw(this.chart.ctx)):this.dodraw(f))};this.dodraw=function(a){var c=this.direction,e="both"==c,f;this.calcRect();d||(d=new m(b.x+0.5*b.width,b.y+0.5*b.height));a.beginPath();if(e||"vertical"==c)f=0.5*this.size.y,a.moveTo(d.x,0===f?b.y:d.y-f),a.lineTo(d.x,0===f?b.y+b.height:d.y+f);if(e||"horizontal"==c)f=0.5*this.size.x,a.moveTo(0===f?b.x:d.x-f,d.y),a.lineTo(0===f?b.x+
b.width:d.x+f,d.y);this.format.stroke.prepare(this.format.stroke.fill,a);a.stroke()}};Tee.CursorTool.prototype=new Tee.Tool;Tee.ToolTip=function(a){function d(){function b(a){e.moveTo(e.oldX+a*e.deltaX,e.oldY+a*e.deltaY);e.autoRedraw&&e.chart.draw()}var a=((new Date).getTime()-e.init)/e.animated;1>a?(b(a),window.requestAnimFrame(d,e)):b(1)}Tee.Annotation.call(this,a);this.visible=!1;this.currentSeries=null;this.currentIndex=-1;this.timID=null;this.autoHide=!1;this.delay=1E3;this.animated=100;this.autoRedraw=
!0;this.render="dom";this.hide=function(){var b="dom"===this.render;if(this.visible||b){if(this.onhide)this.onhide(this);this.visible=!1;this.autoRedraw&&(b?Tee.DOMTip.hide():this.chart.draw());this.currentIndex=-1;this.currentSeries=null}};var b=function(b){b&&b[0].hide()};this.mousemove=function(a){var f=this.chart.series,e=f.count(),d=null,j=-1;if(this.chart.chartRect.contains(a))for(e-=1;0<=e;e--){var i=f.items[e];if(i.visible&&(j=i.clicked(a),-1!=j)){d=i;break}}if(-1==j)this.hide(),this.currentIndex=
-1,this.currentSeries=null;else if(j!=this.currentIndex||d!=this.currentSeries)if(this.currentIndex=j,this.currentSeries=d)this.refresh(d,j),this.autoHide&&0<this.delay&&(clearTimeout(this.timID),this.timID=window.setTimeout(b,this.delay,[this]))};var e=null;this.refresh=function(b,f){var h="dom"===this.render;this.visible=!h;this.text=b.markText(f);this.ongettext&&(this.text=this.ongettext(this,this.text,b,f));if(""!==this.text){this.resize();var g=new m;b.calc(f,g);g.x-=0.5*this.bounds.width;g.y-=
1.5*this.bounds.height;0>g.x&&(g.x=0);0>g.y&&(g.y=0);!h&&!this.autoHide&&0<this.animated&&!isNaN(this.position.x)&&!isNaN(this.position.y)?(this.oldX=this.position.x,this.oldY=this.position.y,this.deltaX=g.x-this.oldX,this.deltaY=g.y-this.oldY,this.init=(new Date).getTime(),e=this,window.requestAnimFrame(d,this)):(this.moveTo(g.x,g.y),this.autoRedraw&&(h?Tee.DOMTip.show(this.text,"auto",a.canvas):this.chart.draw()));if(this.onshow)this.onshow(this,b,f)}}};Tee.ToolTip.prototype=new Tee.Annotation;
Tee.RainbowPalette=function(){return"#FF0000 #FF7F00 #FFFF00 #00FF00 #0000FF #6600FF #8B00FF".split(" ")};Tee.Palette=function(a){this.colors=a};Tee.Palette.prototype.get=function(a){return this.colors[-1==a?0:a%this.colors.length]};I.prototype=new Tee.Annotation;x.adjustRect=function(){if(this.visible){var a=0,d=this.labels,b=this.chart.chartRect;if((this.firstSeries=this.hasAnySeries())&&this.visible)this.checkMinMax(),d.checkStyle(),b.automatic&&!this.custom&&(d.visible&&(d.format.font.prepare(),
a=this.horizontal?d.format.textHeight("Wj"):this.minmaxLabelWidth(),d.alternate&&(a*=2),a+=d.padding),this.ticks.visible&&(a+=this.ticks.length),d=this.title,d.visible&&(d.text&&""!==d.text)&&(d.resize(),a+=d.bounds.height),this.horizontal?this.otherSide?b.setTop(b.y+a):b.height-=a:this.otherSide?b.width-=a:b.setLeft(b.x+a))}};x.prototype.setPos=function(a,d){this.startPos=a+0.01*this.start*d;this.endPos=a+0.01*this.end*d;this.axisSize=this.endPos-this.startPos};x.calcRect=function(){if(this.firstSeries){this.checkMinMax();
var a=this.chart.chartRect,d=this.bounds,b=this.horizontal;b?(d.y=this.otherSide?a.y:a.y+a.height,d.width=a.width,this.setPos(a.x,a.width)):(d.x=this.otherSide?a.x+a.width:a.x,d.height=a.height,this.setPos(a.y,a.height));this.calcAxisScale();if(this.automatic){var d=this.chart.series,d=b?d.horizMargins():d.vertMargins(),e=0<d.x,c=0<d.y;e&&(this.minimum-=this.fromSize(d.x));c&&(this.maximum+=this.fromSize(d.y));(e||c)&&this.calcAxisScale()}this.calcScale();var d=0.01*(b?a.height:a.width)*this.position,
e=this.chart.walls,c=0,f=e.visible&&this.chart.aspect.view3d;b?(f&&e.bottom.visible&&(c=e.bottom.size),this.axisPos=this.otherSide?a.y+d:a.getBottom()+c-d):(f&&e.left.visible&&(c=e.left.size),this.axisPos=this.otherSide?a.getRight()-d:a.x-c+d)}};x.draw=function(){if(this.visible&&this.firstSeries){this.z=this.otherSide?this.chart.walls.back.format.z:0;""!==this.format.stroke.fill&&this.drawAxis();this.roundMin()+1E3*this.increm>this.maximum&&(this.grid.visible&&this.drawGrids(),this.ticks.visible&&
this.drawTicks(this.ticks,1,0),this.innerTicks.visible&&this.drawTicks(this.innerTicks,-1,0),this.minorTicks.visible&&this.drawTicks(this.minorTicks,1,Math.max(0,this.minorTicks.count)),this.labels.visible&&this.drawLabels());var a=this.title;a.visible&&(a.text&&""!==a.text)&&this.drawTitle()}};N.prototype=new Tee.Annotation;Tee.Series=function(a,d){this.chart=null;this.data={values:[],labels:[],source:null};this.yMandatory=!0;this.horizAxis="bottom";this.vertAxis="left";this.sequential=!0;var b=
this.format=new Tee.Format(this.chart),e=this.hover=new Tee.Format(this.chart),c=e.shadow;b.fill="";b.stroke.fill="";this.visible=!0;e.stroke.size=3;e.fill="";e.stroke.fill="red";c.visible=!0;c.color="red";c.blur=10;c.width=0;c.height=0;this.cursor="default";this.over=-1;this.marks=new N(this,this.chart);this.palette=new Tee.Palette;this.colorEach="auto";this.useAxes=!0;this.decimals=2;this._paintWalls=this._paintAxes=!0;this.init=function(b,a){"object"===typeof b&&b&&(b instanceof Array?(this.data.values=
b,a instanceof Array&&(this.data.labels=a)):b instanceof Tee.Chart?(this.chart=b,a instanceof Array&&(this.data.values=a)):(this.data.source=b,this.refresh()))};this.init(a,d);this.getFill=function(b,a){var c=this.palette,c=c&&c.colors?c.get(b):null;return null===c?this.isColorEach||!a?this.chart.palette.get(b):a.fill:c};this.isNull=function(b){return null===this.data.values[b]};this.getFillStyle=function(a,c){return b.gradient.visible?b.gradient.create(a,c):c};this.title="";this.titleText=function(b){return this.title||
"Series "+b.toString()};this.refresh=function(b){this.data.source?this.data.source instanceof HTMLTextAreaElement?(parseText(this.data,this.data.source.value),this.chart&&this.chart.draw()):this.data.source instanceof HTMLInputElement?Tee.doHttpRequest(this,this.data.source.value,function(b,a){parseText(b.data,a);b.chart.draw()},function(a,c){b&&b(this,a,c)}):b&&b(this):this.data.xml?(parseXML(this,this.data.xml),this.chart.draw()):this.data.json&&(parseJSON(this,this.data.json),this.chart.draw())};
this.valueOrLabel=function(b){var a=this.data.labels[b];if(!a||""===a)a=this.valueText(b);return a};this.toPercent=function(b){var a=this.data.values;return(100*Math.abs(a[b])/O(a)).toFixed(this.decimals)+" %"};this.markText=function(b){var a=this.marks,c=this.dataText(b,a.style,!1);return a.ongettext?a.ongettext(this,b,c):c};this.associatedToAxis=function(b){return b.horizontal?"both"==this.horizAxis||this._horizAxis==b:"both"==this.vertAxis||this._vertAxis==b};this.bounds=function(b){var a=this._horizAxis,
c=this._vertAxis;b.x=a.calc(this.minXValue());b.width=a.calc(this.maxXValue())-b.x;b.y=c.calc(this.maxYValue());b.height=c.calc(this.minYValue())-b.y};this.calcStack=function(b,a,c){var c=this.pointOrigin(b,!1)+c,e=this.mandatoryAxis;a.x=this.notmandatory.calc(this.data.x?this.data.x[b]:b);this.isStack100?(b=this.pointOrigin(b,!0),a.y=0===b?e.endPos:e.calc(100*c/b)):a.y=e.calc(c);this.yMandatory||(b=a.x,a.x=a.y,a.y=b)};this.pointOrigin=function(b,a){var c=0,e,d,k=this.chart.series.items,l;for(e=0;e<
k.length&&!(d=k[e],!a&&d==this);e++)l=d.data.values,d.visible&&(d.constructor==this.constructor&&l.length>b)&&(d=l[b],void 0!==d&&(c+=a&&0>d?-d:d));return c};this.doHover=function(b){var a=this.chart;if(b!=this.over){if(a.onhover)a.onhover(this,b);this.over=b;this.hover.enabled&&window.requestAnimFrame(function(){a.draw()})}}};Tee.Series.prototype.initZ=function(a,d){var b=this.format;b.z=a/d;b.depth=1/d;this.marks.format.z=b.z+0.5*b.depth};Tee.Series.prototype.setChart=function(a,d){a.chart=d;a.recalcAxes();
a.format.setChart(d);a.marks.setChart(d);a.hover.setChart(d)};Tee.Series.prototype.calc=function(a,d){var b=this.data,e=this.notmandatory.calc(b.x?b.x[a]:a),b=this.mandatoryAxis.calc(b.values[a]);d.x=this.yMandatory?e:b;d.y=this.yMandatory?b:e};Tee.Series.prototype.recalcAxes=function(){var a=this.chart.axes;this._horizAxis=this.horizAxis instanceof x?this.horizAxis:"top"==this.horizAxis?a.top:a.bottom;this._vertAxis=this.vertAxis instanceof x?this.vertAxis:"right"==this.vertAxis?a.right:a.left;this.mandatoryAxis=
this.yMandatory?this._vertAxis:this._horizAxis;this.notmandatory=this.yMandatory?this._horizAxis:this._vertAxis};Tee.Series.prototype.getRect=function(){return new n};Tee.Series.prototype.clicked=function(){return-1};Tee.Series.prototype.valueText=function(a){return(a=(this.data._old||this.data.values)[a])?a instanceof Date?a.format?a.format(this.dateFormat):a.toString():this.valueFormat?a.toLocaleString():(a|0)==a?a.toFixed(0):a.toFixed(this.decimals):"0"};Tee.Series.prototype.labelOrTitle=function(a){return this.data.labels[a]||
this.title};Tee.Series.prototype.mousedown=function(){return!1};Tee.Series.prototype.mousemove=function(a){if(this.hover.enabled||"default"!=this.cursor){var d=this.clicked(a);this.doHover(d);if("default"!=this.cursor&&-1!=d){this.chart.newCursor||(this.chart.newCursor=this.cursor);return}}d=this.marks;if(d.visible){var b=this.data.values.length,e=new m,c;for(c=0;c<b;c+=d.drawEvery)if(!this.isNull(c)&&(this.markPos(c,e),d.canDraw(e.x,e.y,c)&&d.bounds.contains(a))){this.doHover(c);break}}};Tee.Series.prototype.mouseout=
function(){};Tee.Series.prototype.markPos=function(a,d){this.calc(a,d);return!1};Tee.Series.prototype.drawMarks=function(){var a=this.data.values.length,d=new m,b,e;for(b=0;b<a;b+=this.marks.drawEvery)this.isNull(b)||(e=this.markPos(b,d),this.marks.drawMark(d.x,d.y,b,e))};Tee.Series.prototype.horizMargins=function(){};Tee.Series.prototype.vertMargins=function(){};Tee.Series.prototype.minXValue=function(){return this.data.x&&0<this.data.x.length?Math.min.apply({},this.data.x):0};Tee.Series.prototype.minYValue=
function(){var a=this.data.values;return 0<a.length?Math.min.apply({},a):0};Tee.Series.prototype.maxXValue=function(){if(this.data.x)return 0<this.data.x.length?Math.max.apply({},this.data.x):0;var a=this.data.values.length;return 0===a?0:a-1};Tee.Series.prototype.maxYValue=function(){var a=this.data.values,d=a.length,b,e,c;if(0<d){c=Math.max.apply({},a);if(c!==c)for(b=0;b<d;b++)e=a[b],void 0!==e&&(c!==c?c=e:e>c&&(c=e));return c===c?c:0}return 0};Tee.Series.prototype.calcColorEach=function(){this.isColorEach=
"yes"==this.colorEach};Tee.Series.prototype.stackMaxValue=function(){if("100"==this.stacked)return 100;var a=Tee.Series.prototype.maxYValue;if("no"==this.stacked)return a.call(this);for(var a=a.call(this),d=this.data.values,b=d.length,e;b--;)e=d[b],void 0===e&&(e=0),a=Math.max(a,this.pointOrigin(b,!1)+e);return a};Tee.Series.prototype.dataText=function(a,d,b,e){function c(b,a){return e?f?[b,a]:[b,""]:b+(a?" "+a:"")}var f=b?this.labelOrTitle(a):this.data.labels[a];return"value"==d?this.valueText(a):
"percent"==d?this.toPercent(a):"percentlabel"==d?c(this.toPercent(a),f):"valuelabel"==d||"auto"==d?c(this.valueText(a),f):"label"==d?f||"":"index"==d?a.toFixed(0):"labelvalue"==d?c(f,this.valueText(a)):"labelpercent"==d?c(f,this.toPercent(a)):this.valueOrLabel(a)};Tee.Series.prototype.legendText=Tee.Series.prototype.dataText;Tee.Series.prototype.count=function(){return this.data.values.length};Tee.Series.prototype.legendCount=function(){return this.count()};Tee.Series.prototype.legendColor=function(a){return this.isColorEach&&
-1!=a?this.getFill(a):this.format.fill};Tee.Series.prototype.addRandom=function(a,d,b){d||(d=1E3);a||(a=5);var e=this.data;e.values.length=a;b&&(e.x=Array(a));if(0<a){e.values[0]=Math.random()*d;b&&(e.x[0]=Math.random()*d);for(var c=1;c<a;c++)e.values[c]=e.values[c-1]+Math.random()*d-0.5*d,b&&(e.x[c]=Math.random()*d)}return this};Tee.Series.prototype.doSort=function(a,d){if("none"==a)return null;for(var b=this.data.values,e=b.length,c=Array(e),f=0;f<e;f++)c[f]=f;if("labels"==a){var b=this.data.labels,
h,g,j=d?-1:1,i=d?1:-1;c.sort(function(a,c){h=b[a].toLowerCase();g=b[c].toLowerCase();return h<g?j:h==g?0:i})}else c.sort(d?function(a,c){return b[a]-b[c]}:function(a,c){return b[c]-b[a]});return c};J.prototype.each=function(a){for(var d=this.items.length,b=0;b<d;b++)a(this.items[b])};J.prototype.eachAxis=function(a,d){for(var b=this.items.length,e;b--;)e=this.items[b],e.visible&&((!a||e.associatedToAxis(a))&&(e.__alwaysDraw||0<e.count()))&&d(e)};Tee.Chart=function(a,d,b){function e(a){f.chart.addSeries(new (b||
Tee.Bar)(f.chart)).data.values=a}var c="undefined"!=typeof navigator?navigator.userAgent.toLowerCase():"";this.isChrome=-1<c.indexOf("chrome");this.isAndroid=-1<c.indexOf("android");this.isMozilla=window.mozRequestAnimationFrame;a&&(this.canvas="undefined"!==typeof HTMLCanvasElement&&a instanceof HTMLCanvasElement?a:"string"==typeof a?document.getElementById(a):a);this.canvas||(this.canvas=document.createElement("canvas"),this.canvas.width=600,this.canvas.height=400);var f=this.canvas;this.bounds=
(this.__webgl=f.__webgl)||0===f.clientWidth?new n(0,0,f.width,f.height):new n(0,0,f.clientWidth,f.clientHeight);this.chartRect=new n;this.chartRect.automatic=!0;this.chartRect.setFrom(this.bounds);this.palette=new Tee.Palette("#4466a3 #f39c35 #f14c14 #4e97a8 #2b406b #1d7b63 #b3080e #f2c05d #5db79e #707070 #f3ea8d #b4b4b4".split(" "));var h=this.aspect={chart:this,view3d:this.__webgl,ortogonal:!this.__webgl,rotation:0,elevation:315,perspective:50,clip:!0,_orthox:10,_orthoy:8,clipRect:function(b){var a=
this.chart.ctx;a.save();a.beginPath();this.view3d?a.rect(b.x,b.y-this._orthoy,b.width+this._orthox,b.height+this._orthoy):a.rect(b.x,b.y,b.width,b.height);a.clip()}};this.panel=new U(this);this.walls={chart:this,visible:!0,left:new F(this),right:new F(this),bottom:new F(this),back:new F(this),draw:function(b,a){var c,e=this.chart.ctx,f=this.transparency,d=e.beginParent;this.visual=d?e.beginParent():null;0<f&&(c=e.globalAlpha,e.globalAlpha=(1-f)*c);var g=this.back.bounds;g.setFrom(b);if(a.view3d){var h=
this.bottom.visible?this.bottom.size:0,j=this.left.size;0<j&&(g.x-=j,g.width+=j);0<h&&(g.height+=h);this.left.bounds.set(b.x-j,b.y,j,b.height+h);this.bottom.bounds.set(b.x,b.getBottom(),b.width,h);this.back.format.depth=this.back.size}!this.back.visible||this.back.draw();this.chart.aspect.view3d&&(this.left.visible&&this.left.draw(),this.bottom.visible&&this.bottom.draw(),this.right.visible&&this.right.draw());0<f&&(e.globalAlpha=c);d&&e.endParent()}};a=this.walls.back.format;a.fill="rgb(240,240,240)";
a.shadow.visible=!0;a.z=1;a=this.walls.left;a.format.fill="#BBAA77";a.format.depth=1;a.size=2;a=this.walls.bottom;a.format.depth=1;a.size=2;this.walls.right.visible=!1;this.axes=new W(this);this.legend=new V(this);this.series=new J(this);this.title=new I(this,"blue");this.title.text="TeeChart";this.title.format.z=1;this.footer=new I(this,"red");this.footer.format.z=0;this.zoom=new S(this);this.scroll=new T(this);this.tools=new R(this);this.oldPos=new m;this.calcMouse=function(b,a){if(null===b.pageX){var c=
document.documentElement&&null!==document.documentElement.scrollLeft?document.documentElement:document.body;a.x=b.clientX+c.scrollLeft;a.y=b.clientY+c.scrollTop}else a.x=b.pageX,a.y=b.pageY;c=this.canvas;if(c.getBoudingClientRect)c=c.getBoundingClientRect(),a.x-=c.left,a.y-=c.top;else if(c.offsetParent){do a.x-=c.offsetLeft,a.y-=c.offsetTop,c=c.offsetParent;while(c)}};var g=new m(0,0);this.domousemove=function(b){var a=this.chart;if(!a.ctx)return!1;b=b||window.event;b.touches&&(b=b.touches[b.touches.length-
1]);a.calcMouse(b,g);if(a.scroll.active){var c=a.scroll.direction,e="both"==c,f;if(e||"horizontal"==c)f=a.axes.bottom.fromSize(a.oldPos.x-g.x),a.axes.top.scroll(f),a.axes.bottom.scroll(f);if(e||"vertical"==c)f=-a.axes.left.fromSize(a.oldPos.y-g.y),a.axes.left.scroll(f),a.axes.right.scroll(f);a.oldPos.x=g.x;a.oldPos.y=g.y;a.scroll.done=!0;if(a.onscroll)a.onscroll(b);a.scroll.done&&window.requestAnimFrame(function(){a.draw()});return!1}if(a.zoom.active){if(g.x!=a.oldPos.x||g.y!=a.oldPos.y)a.zoom.change(g),
window.requestAnimFrame(function(){a.draw()}),a.zoom.done=!0;return!1}a.newCursor=null;a.tools.mousemove(g);a.series.mousemove(g);a.legend.mousemove(g);a.title.mousemove(g);b=this.chart.canvas.style;a.newCursor?b.cursor!=a.newCursor&&(a.oldCursor=b.cursor,b.cursor=a.newCursor):void 0!==a.oldCursor&&b.cursor!=a.oldCursor&&(b.cursor=a.oldCursor);return!0};var j=new m(0,0);this.domousedown=function(b){var b=b||window.event,a=!1,c=this.chart;c.calcMouse(b.touches?b.touches[0]:b,j);var e=c.series.anyUsesAxes()&&
c.chartRect.contains(j);b.touches?1<b.touches.length?(c.zoom.active=c.zoom.enabled&&e,c.zoom.active&&(c.scroll.active=!1)):(c.scroll.active=c.scroll.enabled&&e,c.scroll.active&&(c.zoom.active=!1)):(c.zoom.active=b.button==c.zoom.mouseButton&&c.zoom.enabled&&e,c.scroll.active=b.button==c.scroll.mouseButton&&c.scroll.enabled&&e);c.zoom.done=!1;c.scroll.done=!1;c.oldPos=j;0===b.button?((a=c.tools.mousedown(b))||(a=c.series.mousedown(b)),c.canvas.oncontextmenu=null):2==b.button&&(c.canvas.oncontextmenu=
function(){return!1});a?c.zoom.active=c.scroll.active=!1:a=c.zoom.active||c.scroll.active;b.preventDefault?b.preventDefault():b.cancelBubble=!0;a&&(b=b.target||b.fromElement)&&b.setCapture&&b.setCapture();return!a};this.domouseup=function(b){var b=b||window.event,a=this.chart,c;a.zoom.active=!1;a.scroll.active=!1;if(a.zoom.done){if(a.zoom.apply()&&a.onzoom)a.onzoom();a.draw();c=!0}else if(c=a.scroll.done,!c&&(c=a.series.clicked(a.oldPos),!c&&(c=a.tools.clicked(a.oldPos),!c&&(c=a.title.clicked(a.oldPos))&&
a.title.onclick)))a.title.onclick(a.title);a.zoom.old=null;a.zoom.done=!1;a.scroll.done=!1;c?b.preventDefault?b.preventDefault():b.cancelBubble=!0:a.canvas.oncontextmenu=null;(b=b.target||b.fromElement)&&b.releaseCapture&&b.releaseCapture()};f.onmousedown=f.ontouchstart=this.domousedown;f.onmouseup=f.ontouchstop=this.domouseup;f.onmousemove=f.ontouchmove=this.domousemove;this._doWheel=function(b){var a=this.chart;if(a.zoom.wheel.enabled){var b=b||window.event,c=a.zoom.wheel.factor*(b.wheelDelta?b.wheelDelta/
120:b.detail?-b.detail/3:0);if(0<Math.abs(c)){var e={x:0,y:0};a.calcMouse(b,e);a.chartRect.contains(e)&&(a.axes.each(function(){var b=this.maximum-this.minimum;0<b&&(b=0.05*c*b,this.setMinMax(this.minimum+b,this.maximum-b))}),a.draw(),b.returnValue=!1,b.preventDefault&&b.preventDefault())}}};f.addEventListener&&f.addEventListener("DOMMouseScroll",this._doWheel,!1);f.onmousewheel=this._doWheel;f.onmouseout=function(b){b&&!b.target.setCapture&&(this.chart.scroll.active=!1);this.chart.series.mouseout();
this.chart.tools.mouseout()};this.addSeries=function(b){b.setChart(b,this);var a=this.series.items,c=a.indexOf(b);-1==c&&(c=a.push(b)-1);""===b.title&&(b.title="Series"+(1+c).toString());""===b.format.fill&&(b.format.fill=this.palette.get(c));return b};this.removeSeries=function(b){var a=this.series.items,b=a.indexOf(b);-1!=a&&a.splice(b,1)};f.chart=this;if(d&&0<d.length)if(d[0]instanceof Array)for(a=0;a<d.length;a++)e(d[a]);else e(d);this.getSeries=function(b){return this.series.items[b]};this.draw=
function(b){var a=this.series,c=this.chartRect,b=this.ctx=b||(this.canvas.getContext?this.canvas.getContext("2d"):null);if(!b)throw"Canvas does not provide Context";c.automatic&&c.setFrom(this.bounds);for(var e=a.items.length,f,d=!1,g=!1,j=1,t=a.visibleCount(),m=0;e--;)f=a.items[e],f.visible&&(f.initZ(m,t),m++,f._paintAxes&&(d=!0),f._paintWalls&&(g=!0),f.maxZ&&f.maxZ>j&&(j=f.maxZ));this.walls.left.format.depth=j;this.walls.bottom.format.depth=j;this.walls.back.format.z=j;this.panel.draw();c.automatic&&
this.panel.margins.apply(c);this.title.tryDraw(!0);this.footer.tryDraw(!1);a.beforeDraw();this.legend.visible&&(this.legend.calcrect(),this.legend.draw());h.view3d&&!this.__webgl&&(c.y+=h._orthoy,c.height-=h._orthoy,c.width-=h._orthox);var a=this.axes,n;this.series.anyUsesAxes()&&(a.each(x.adjustRect),a.each(x.calcRect),this.walls.visible&&g&&this.walls.draw(c,this.aspect),a.visible&&d&&(0<a.transparency&&(n=b.globalAlpha,b.globalAlpha=(1-a.transparency)*n),c=b.beginParent,a.visual=c?b.beginParent():
null,a.each(x.draw),c&&b.endParent(),0<a.transparency&&(b.globalAlpha=n)));this.series.draw();this.tools.draw();this.zoom.active&&this.zoom.draw();if(this.ondraw)this.ondraw(this)};this.toImage=function(b,a,c){if(b=document.getElementById(b))b.src=""!==a?this.canvas.toDataURL(a,c):this.canvas.toDataURL()}};Tee.CustomBar=function(a,d){Tee.Series.call(this,a,d);this.sideMargins=100;this.useOrigin=!0;this.origin=0;this.marks.visible=!0;this.marks.location="end";this.hover.enabled=!0;this.offset=0;this.barSize=
70;this.barStyle="bar";var b=this.format;b.fill="";b.stroke.fill="black";b.shadow.visible=!0;b.round.x=4;b.round.y=4;b.gradient.visible=!0;b.depth=1;this.stacked="no";this.drawBar=function(a){var c=b.depth,e=b.z,f=this.chart.ctx;b.depth=0.5*Math.min(this.yMandatory?a.width:a.height,200)/100;"side"!==this.stacked&&(b.z+=0.5*(1-b.depth));if("bar"===this.barStyle)b.cube(a);else if("line"===this.barStyle){var d;f.beginPath();f.z=b.z+0.5*b.depth;this.yMandatory?(d=a.x+0.5*a.width,f.moveTo(d,a.y),f.lineTo(d,
a.y+a.height)):(d=a.y+0.5*a.height,f.moveTo(a.x,d),f.lineTo(a.x+a.width,d))}else"cylinder"===this.barStyle?b.cylinder(a,1,this.yMandatory):"cone"===this.barStyle?b.cylinder(a,0,this.yMandatory):b.ellipsePath(this.chart.ctx,a.x+0.5*a.width,a.y+0.5*a.height,a.width,a.height);b.depth=c;b.z=e};this.countAll=function(b){var a=this.chart.series.items,c=0,e=a.length,f,d;for(f=0;f<e&&!(d=a[f],d==this&&b);f++)d.visible&&d.constructor==this.constructor&&(c+=d.data.values.length);return c};var e=new m,c,f=new n,
h={total:0,index:0};this._margin=0;this.calcBarOffset=function(b){var a="sideAll"==this.stacked;this.countall=a?this.countAll(!0):0;a=a?this.countAll():this.data.values.length;1<a&&(b/=a-1);"no"==this.stacked?(b/=h.total,e.x=b*(1==h.total?-0.5:h.index-0.5*h.total),a=h.total):(e.x=0.5*-b,a=1);e.y=0.01*b*this.barSize;this._margin=0.5*a*e.y+0.0050*this.sideMargins*a*(b-e.y);e.x+=0.01*this.offset*b+0.5*(b-e.y)};this.calcStackPos=function(b,a){var e,f,d;this.isStacked?(this.calcStack(b,a,this.data.values[b]),
e=this.pointOrigin(b,!1),d=this.mandatoryAxis,this.isStack100?(f=this.pointOrigin(b,!0),c=0===f?d.endPos:d.calc(100*e/f)):c=d.calc(e)):(this.calc(b,a),"sideAll"==this.stacked&&(f=this.notmandatory.calc(this.countall+b),this.yMandatory?a.x=f:a.y=f))};this.draw=function(){var a=this.data.values.length;if(0<a){this.initOffsets();var d=new m,h=this.chart.ctx;this.hover.enabled||(b.stroke.prepare(),b.shadow.prepare(h));for(var k=this.hover.enabled,l="line"===this.barStyle,q=0;q<a;q++)if(!this.isNull(q)){this.calcStackPos(q,
d);this.calcBarBounds(d,f,e,c);this.drawBar(f);var y=k&&this.over==q,p=y?this.hover:b;h.fillStyle=this.getFillStyle(f,this.getFill(q,""===p.fill?b:p));k&&p.shadow.prepare(h);h.fill();if(l||""!==p.stroke.fill)k&&p.stroke.prepare(),!y&&l&&(h.strokeStyle=h.fillStyle),h.shadowColor="transparent",h.stroke(),p.shadow.visible&&(h.shadowColor=p.shadow.color)}}};this.calcColorEach=function(){this.chart.series.visibleCount(this,Tee.CustomBar,h);this.isColorEach="yes"==this.colorEach||"auto"==this.colorEach&&
1==h.total};this.initOffsets=function(){var b=this.notmandatory,a=this.mandatoryAxis,e=this.yMandatory?this.maxXValue()-this.minXValue():this.maxYValue()-this.minYValue();this.calcBarOffset(0===e?b.axisSize:b.calcSize(e));c=this.useOrigin?a.calc(this.origin):this.yMandatory?a.inverted?a.startPos:a.endPos:a.inverted?a.endPos:a.startPos;b=this.stacked;this.isStacked="no"!==b&&"sideAll"!==b&&"side"!==b;this.isStack100="100"===b};this.clicked=function(b){this.initOffsets();var a=new m,d=this.data.values.length,
h;for(h=0;h<d;h++)if(!this.isNull(h)&&(this.calcStackPos(h,a),this.calcBarBounds(a,f,e,c),f.contains(b)))return h;return-1};this.markPos=function(b,a){var d=this.yMandatory,h=e.x+0.5*e.y,l=this.marks;this.calcStackPos(b,a);if("sideAll"==this.stacked){var q=this.notmandatory.calc(this.countall+b);d?a.x=q:a.y=q}q=this.useOrigin&&this.data.values[b]<this.origin;this.mandatoryAxis.inverted&&(q=!q);"center"==l.location&&(this.calcBarBounds(a,f,e,c),l.canDraw(a.x,a.y,b,q)&&(d?a.y=f.y+0.5*f.height+0.5*l.bounds.height:
a.x=f.x+0.5*f.width-0.5*l.bounds.width));var l=this.chart.aspect,m=l.view3d,p=0,u=0;m&&l.orthogonal&&(p=0.5*l._orthox,u=0.5*l._orthoy);d?(a.x+=m?h+p:h,m&&(a.y-=u)):(a.y+=m?h-u:h,m&&(a.x+=p));return q};this.labelOrTitle=function(b){var a=this.title,c=this.data.labels[b];return 1<h.total?a||c:this.parent.labelOrTitle(b)};this.initZ=function(b,a){var c,e=this.format;if("side"!==this.stacked){e.z=0;for(e.depth=1;1<b;)if(b--,c=this.chart.series.items[b],c.visible&&c.constructor==this.constructor){e.z=
c.z;e.depth=c.depth;break}}else Tee.Series.prototype.initZ.call(this,b,a);this.marks.format.z=e.z+0.5*e.depth}};Tee.CustomBar.prototype=new Tee.Series;Tee.CustomBar.prototype.parent=Tee.Series.prototype;Tee.CustomBar.constructor=Tee.CustomBar;Tee.Bar=function(a,d){Tee.CustomBar.call(this,a,d);this.calc=function(b,a){this.isStacked?this.calcStack(b,a,this.data.values[b]):this.parent.calc.call(this,b,a)};this.horizMargins=function(b){this.initOffsets();b.x=this._margin;b.y=this._margin};this.vertMargins=
function(b){var a=this.marks,c=this.format.stroke,f=this.minYValue()<this.origin;a.visible&&"center"!==a.location&&(b.y=a.arrow.length+a.format.textHeight("Wj")+a.margins.top+a.margins.bottom,c=a.format.stroke);""!==c.fill&&(b.y+=2*c.size+1);f&&(b.x=b.y)};this.maxXValue=function(){return"sideAll"===this.stacked?this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxYValue=function(){if("sideAll"===
this.stacked||"side"===this.stacked){var a=0,e,c=this.chart.series.items,f=c.length,d;for(d=0;d<f;d++)e=c[d],e.visible&&e.constructor===this.constructor&&(e=e.parent.maxYValue.call(e),e>a&&(a=e));return a}return this.stackMaxValue()};this.calcBarBounds=function(a,e,c,f){e.x=a.x+c.x;e.width=c.y;this._vertAxis.inverted?(e.y=f,e.height=a.y-e.y):(e.y=a.y,e.height=f-a.y);0>e.height&&(e.y+=e.height,e.height=-e.height)}};Tee.Bar.prototype=new Tee.CustomBar;Tee.Bar.prototype.parent=Tee.CustomBar.prototype;
Tee.HorizBar=function(a,d){Tee.CustomBar.call(this,a,d);this.yMandatory=!1;this.format.gradient.direction="rightleft";this.maxMarkWidth=function(){var a=0,e,c,f=this.marks,d=this.count(),g;if(f.visible){e=this.marks.format;e.font.prepare();for(c=0;c<d;c+=f.drawEvery)this.isNull(c)||(g=e.textWidth(this.markText(c)+"W"),g>a&&(a=g))}return a};this.horizMargins=function(a){var e=this.marks,c=this.format.stroke,f=this.minXValue()<this.origin;e.visible&&"center"!==e.location&&(a.y=e.arrow.length+this.maxMarkWidth()+
e.margins.left+e.margins.right,c=e.format.stroke);""!==c.fill&&(a.y+=2*c.size+1);f&&(a.x=a.y)};this.vertMargins=function(a){this.initOffsets();a.x+=this._margin;a.y+=this._margin};this.maxYValue=function(){return"sideAll"==this.stacked?this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){return"sideAll"==this.stacked?0:this.parent.minXValue.call(this)};this.minXValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxXValue=
function(){return this.stackMaxValue()};this.calcBarBounds=function(a,e,c,f){e.y=a.y+c.x;e.height=c.y;this._horizAxis.inverted?(e.x=a.x,e.width=f-a.x):(e.x=f,e.width=a.x-e.x);0>e.width&&(e.x+=e.width,e.width=-e.width)}};Tee.HorizBar.prototype=new Tee.CustomBar;Tee.HorizBar.prototype.parent=Tee.CustomBar.prototype;Tee.CustomSeries=function(a,d){Tee.Series.call(this,a,d);this.stacked="no";this.stairs=!1;this.hover.enabled=!0;this.isStack100=this.isStacked=this.hover.line=!1;this.smooth=0;this.pointer=
new function(a,e){this.setChart=function(a){this.chart=a;this.format.setChart(a)};this.chart=a;var c=this.format=new Tee.Format(a);c.shadow.visible=!1;c.fill="";c.gradient.colors=["white","white","white"];c.gradient.visible=!0;c.shadow.visible=!0;this.colorEach=this.visible=!1;this.style="rectangle";this.height=this.width=12;this.draw=function(a,b,c,d){var i=this.chart.ctx;c.z=e.format.z;this.transform&&(i.save(),this.transform(a.x,a.y,b));var b=0.5*this.width,k=0.5*this.height;"cube"==this.style?
(a={x:a.x-b,y:a.y-k,width:this.width,height:this.height},d=Math.max(b,k)/50,c.z=0.5*(e.format.z+e.format.depth)-0.5*d,c.depth=d,c.cube(a),c.draw(i,null,a)):"rectangle"==this.style?c.rectangle(a.x-b,a.y-k,this.width,this.height):"ellipse"==this.style?c.ellipse(a.x,a.y,this.width,this.height):"sphere"==this.style?(c.depth=e.format.depth,c.sphere(a.x,a.y,this.width,this.height)):"cylinder"==this.style?(a={x:a.x-b,y:a.y-k,width:this.width,height:this.height},d=c.gradient,b=d.direction,k=d.colors.slice(0),
d.direction="leftright",d.colors=[d.colors[1],d.colors[0],d.colors[1]],c.cylinder(a,1,!0),c.draw(i,null,a),d.direction=b,d.colors=k):"cone"==this.style?(a={x:a.x-b,y:a.y-k,width:this.width,height:this.height},c.cylinder(a,0,!0),c.draw(i,null,a)):"triangle"==this.style?c.polygon([new m(a.x,a.y-k),new m(a.x-b,a.y+k),new m(a.x+b,a.y+k)]):"downtriangle"==this.style?c.polygon([new m(a.x,a.y+k),new m(a.x-b,a.y-k),new m(a.x+b,a.y-k)]):"diamond"==this.style?c.polygon([new m(a.x,a.y-k),new m(a.x-b,a.y),new m(a.x,
a.y+k),new m(a.x+b,a.y)]):(i.beginPath(),"cross"==this.style&&(i.moveTo(a.x-b,a.y),i.lineTo(a.x+b,a.y),i.moveTo(a.x,a.y-k),i.lineTo(a.x,a.y+k)),"x"==this.style&&(i.moveTo(a.x-b,a.y-k),i.lineTo(a.x+b,a.y+k),i.moveTo(a.x-b,a.y+k),i.lineTo(a.x+b,a.y-k)),c.stroke.prepare(d),i.stroke());this.transform&&i.restore()};this.setSize=function(a){this.height=this.width=a}}(this.chart,this);this.maxYValue=function(){return this.stackMaxValue()};this.calc=function(a,e){this.isStacked?this.calcStack(a,e,this.data.values[a]):
Tee.Series.prototype.calc.call(this,a,e)};this.calcColorEach=function(){this.isColorEach="yes"==this.colorEach||this.pointer.colorEach};this.initZ=function(a,e){var c,d=this.format;if("no"!==this.stacked){d.z=0;for(d.depth=1;1<a;)if(a--,c=this.chart.series.items[a],c.visible&&c.constructor==this.constructor){d.z=c.z;d.depth=c.depth;break}}else Tee.Series.prototype.initZ.call(this,a,e);this.marks.z=d.z+0.5*d.depth}};Tee.CustomSeries.prototype=new Tee.Series;Tee.CustomSeries.prototype.drawPointers=
function(){var a=this.data.values.length,d=this.pointer.format,b="yes"==this.colorEach||this.pointer.colorEach;!b&&""===d.fill&&(d.fill=this.format.fill);var e=new m,c=d.gradient,f,h=d.fill,g=h;!b&&c.visible&&c.setEndColor(h);for(f=0;f<a;f++)this.isNull(f)||(this.calc(f,e),h=this.getFill(f,d),h!=g&&(c.visible?c.setEndColor(h):d.fill=h,g=h),this.getSize(f),this.pointer.draw(e,f,d,h),this.hover.enabled&&this.over==f&&this.pointer.draw(e,f,this.hover,h));b&&(d.fill=g)};Tee.CustomSeries.prototype.setChart=
function(a,d){var b=Tee.Series.prototype.setChart;b(a,d);a.pointer.setChart(d)};Tee.CustomSeries.prototype.clicked=function(a){var d=new m,b=new m,e=this.data.values.length,c;if(this.drawLine&&0<e&&(this.hover.line||!this.pointer.visible)){this.calc(0,d);for(c=1;c<e;c++){this.calc(c,b);if(P(a,d,b,3))return c;d.x=b.x;d.y=b.y}}if(this.pointer.visible){d=new n;b=this.pointer;for(c=e-1;0<=c;c--)if(!this.isNull(c)&&(this.calc(c,d),this.getSize(c),d.x-=0.5*b.width,d.width=b.width,d.y-=0.5*b.height,d.height=
b.height,d.contains(a)))return c}return-1};Tee.CustomSeries.prototype.horizMargins=function(a){var d=this.pointer,b=d.format.stroke;d.visible&&(a.x=a.y=(""!==b.fill?b.size:0)+1+0.5*d.width)};Tee.CustomSeries.prototype.vertMargins=function(a){var d=this.pointer,b=d.format.stroke;d.visible&&(a.x=a.y=(""!==b.fill?b.size:0)+1+0.5*d.height)};Tee.CustomSeries.prototype.getSize=function(){};Tee.Line=function(a,d){Tee.CustomSeries.call(this,a,d);this.drawLine=!0;var b=this.format;b.shadow.visible=!0;b.shadow.blur=
10;b.lineCap="round";this.doDrawLine=function(a){var c=new m,d,h=this.data.values.length,g,j=0,i=h,k=this.notmandatory;!this.smooth&&!this.data.x&&(j=Math.max(0,(k.minimum|0)-1),i=Math.min(h,(k.maximum|0)+2));k=this.chart.aspect.view3d;a.beginPath();if(0<this.smooth&&"undefined"!==typeof Tee.drawSpline){d=Array(2*h);for(g=0;g<h;g++)this.calc(g,c),d[2*g]=c.x,d[2*g+1]=c.y;a.spline?a.spline(d):Tee.drawSpline(a,d,this.smooth,!0)}else for(g=j;g<i;g++)this.isNull(g)||(this.calc(g,c),g==j?a.moveTo(c.x,c.y):
(this.stairs&&a.lineTo(d,c.y),a.lineTo(c.x,c.y)),d=c.x);h=b.stroke;this.chart.isChrome&&b.shadow.visible&&(h.size=Math.max(1.1,h.size));a.z=b.z;a.depth=b.depth;c=h.fill;""===c&&(c=b.fill);h.prepare(c);b.shadow.prepare(a);k&&(a.fillStyle=b.fill,a.fill());""!==c&&a.stroke()};this.draw=function(){0<this.data.values.length&&(this.isStacked="no"!=this.stacked,this.isStack100="100"==this.stacked,this.drawLine&&this.doDrawLine(this.chart.ctx),this.pointer.visible&&this.drawPointers())}};Tee.Line.prototype=
new Tee.CustomSeries;Tee.PointXY=function(a,d){Tee.Line.call(this,a,d);this.hover.enabled=!0;this.pointer.visible=!0;this.drawLine=!1};Tee.PointXY.prototype=new Tee.Line;Tee.Series.prototype.cellRect=function(a,d,b){var e={total:0,index:-1};a.setFrom(this.chart.chartRect);this.chart.series.visibleCount(this,b,e);if(d&&1<e.total){d=Math.round(Math.sqrt(e.total));b=Math.round(e.total/d);if(a.width>a.height)var c=d,d=b,b=c;a.width/=d;a.x+=1.03*(e.index%d)*a.width;a.height/=b;a.y+=1.03*(e.index/d|0)*
a.height;a.width*=0.94;a.height*=0.94}return a};Tee.Pie=function(a,d){function b(a,b){b.x=i.x+Math.cos(a)*j;b.y=i.y+Math.sin(a)*j}Tee.Series.call(this,a,d);this.marks.style="percent";this.rotation=this.donut=0;this.colorEach="yes";this.useAxes=!1;var e=this.format;e.stroke.fill="black";e.shadow.visible=!0;e.gradient.visible=!0;e.gradient.direction="radial";e.gradient.colors=["white","white","white"];this.hover.enabled=!0;this.sort="values";this.orderAscending=!1;this.explode=null;this.marks.visible=
!0;this.concentric=!1;this.getValue=function(a){return this.data.values[a]};this.calcCenter=function(a,b,c,e){if(this.explode&&(a=this.explode[a]))a=0.01*b*a,e.x+=a*Math.cos(c),e.y+=a*Math.sin(c)};this.clicked=function(a){var b=this.chart.ctx,c=this.data.values.length,e,d;if(b.isPointInPath){q=l=Math.PI*this.rotation/180;for(e=0;e<c;e++)if(d=k?k[e]:e,!this.isNull(d)&&(this.slice(b,d),b.isPointInPath(a.x,a.y)))return d}return-1};var c,f,h,g,j,i={x:0,y:0},k,l,q,y;this.getCenter=function(a){a.x=i.x;
a.y=i.y;return g};this.slice=function(a,d){var k=new m;q+=2*Math.PI*(Math.abs(this.data.values[d])/c);i.x=f;i.y=h;this.calcCenter(d,g,0.5*(l+q),i);0===this.donut?(k.x=i.x,k.y=i.y):b(l,k);this.chart.__webgl?(b(2*Math.PI-l,k),a.slice(k,i,g,l,q,j,e.tube,e.beveled)):(a.beginPath(),a.moveTo(k.x,k.y),a.arc(i.x,i.y,g,l,q,!1),0!==this.donut&&(b(q,k),a.lineTo(k.x,k.y),a.arc(i.x,i.y,j,q,l,!0)),a.closePath());d==this.over&&(y=l);l=q};this.fill=function(a){return this.getFillStyle(this.chart.chartRect,this.getFill(a))};
this.slices=function(a){var b=this.chart.ctx,c=this.data.values.length,d,f;q=l=Math.PI*this.rotation/180;b.z=0.5;b.depth=1;for(d=0;d<c;d++)f=k?k[d]:d,this.isNull(f)||(this.slice(b,f),a?e.shadow.prepare(b):b.fillStyle=this.fill(f),b.fill(),a||(f=e.stroke,""!==f.fill&&(f.prepare(),b.stroke())))};var p=new n;this.draw=function(){if(0<this.data.values.length){var a=0,b=this.marks;e.shadow.visible&&(a+=2*e.shadow.height);b.visible&&(b.format.font.prepare(),a+=b.format.textHeight("Wj")+0.5*b.arrow.length);
this.cellRect(p,!this.concentric,Tee.Pie);f=p.x+0.5*p.width;h=p.y+0.5*p.height;g=0.5*p.width;a=0.5*(p.height-2*a);0>a&&(a=0);a<g&&(g=a);j=0.01*g*this.donut;c=O(this.data.values);k=this.doSort(this.sort,this.orderAscending);this.chart.__webgl||this.slices(!0);this.slices(!1);this.hover.enabled&&-1!=this.over&&(a=this.hover,""!==a.stroke.fill&&(q=l=y,b=this.chart.ctx,this.slice(b,this.over),b.fillStyle=this.fill(this.over),a.draw(b,null,p)))}};this.drawMarks=function(){var a=Math.PI*this.rotation/180,
b=a,e=this.data.values,d=e.length,j,l;this.marks.format.z=0.5;for(l=0;l<d;l+=this.marks.drawEvery)j=k?k[l]:l,this.isNull(j)||(a+=2*Math.PI*(Math.abs(e[j])/c),b=0.5*(b+a),i.x=f,i.y=h,this.calcCenter(l,g,b,i),this.marks.drawPolar(i,g,b,j),b=a)}};Tee.Pie.prototype=new Tee.Series;Tee.Area=function(a,d){Tee.CustomSeries.call(this,a,d);this.useOrigin=!1;this.origin=0;this.drawLine=!0;var b=this.format;b.shadow.visible=!0;b.lineCap="round";b.stroke.fill="black";b.fill="";b.beveled=!0;b.depth=1;b.z=0.5;var e=
new n;this.draw=function(){var a=this.data.values.length;if(0<a){var d=this.mandatoryAxis,h=this.notmandatory,g,j=this.yMandatory;g=this.useOrigin?d.calc(this.origin):j&&d.inverted||!j&&!d.inverted?d.startPos:d.endPos;this.isStacked="no"!=this.stacked;this.isStack100="100"==this.stacked;var i=new m,k,l,d=this.chart.ctx,q,y=this.isStacked,p=0,u=a;!this.smooth&&!this.data.x&&(p=Math.max(0,(h.minimum|0)-1),u=Math.min(a,(h.maximum|0)+2));d.depth=b.depth;d.z=b.z;d.beginPath();if(0<this.smooth&&"undefined"!==
typeof Tee.drawSpline){q=Array(2*a);for(l=0;l<a;l++)this.calc(l,i),q[2*l]=i.x,q[2*l+1]=i.y;h=j?q[0]:q[1];d.spline?d.spline(q,!0):Tee.drawSpline(d,q,this.smooth,!0);if(y){var s=0;for(l=a-1;0<=l;l--)this.calcStack(l,i,0),q[s++]=i.x,q[s++]=i.y;d.lineTo(q[0],q[1]);d.spline?d.spline(q,!0):Tee.drawSpline(d,q,this.smooth,!1)}}else if(this.calc(p,i),d.moveTo(i.x,i.y),h=j?i.x:i.y,k=j?i.y:i.x,this.stairs)for(l=p+1;l<u;l++)this.calc(l,i),d.lineTo(i.x,k),d.lineTo(i.x,i.y),k=j?i.y:i.x;else for(l=p+1;l<u;l++)this.calc(l,
i),d.lineTo(i.x,i.y);if(y){if(0===this.smooth)for(l=u-1;l>=p;l--)this.calcStack(l,i,0),this.stairs?(d.lineTo(i.x,k),d.lineTo(i.x,i.y),k=j?i.y:i.x):d.lineTo(i.x,i.y)}else j?(d.lineTo(i.x,g),d.lineTo(h,g)):(d.lineTo(g,i.y),d.lineTo(g,h));d.closePath();a=b.gradient;a.visible&&(a.colors[a.colors.length-1]=b.fill);this.bounds(e);d.__webgl&&(d.beveled=b.beveled);b.draw(d,null,e);this.pointer.visible&&this.drawPointers()}};this.minYValue=function(){var a=this.yMandatory?Tee.Series.prototype.minYValue.call(this):
Tee.Series.prototype.minXValue.call(this);return this.yMandatory?this.useOrigin?Math.min(a,this.origin):a:a};this.minXValue=function(){var a=this.yMandatory?Tee.Series.prototype.minXValue.call(this):Tee.Series.prototype.minYValue.call(this);return this.yMandatory?a:this.useOrigin?Math.min(a,this.origin):a};this.maxYValue=function(){var a=this.yMandatory?this.stackMaxValue():Tee.Series.prototype.maxXValue.call(this);return this.yMandatory?this.useOrigin?Math.max(a,this.origin):a:a};this.maxXValue=
function(){var a=this.yMandatory?Tee.Series.prototype.maxXValue.call(this):this.stackMaxValue();return this.yMandatory?a:this.useOrigin?Math.max(a,this.origin):a};this.vertMargins=function(a){this.yMandatory&&""!==b.stroke.fill&&(a.y+=b.stroke.size+2)};this.horizMargins=function(a){!this.yMandatory&&""!==b.stroke.fill&&(a.y+=b.stroke.size+2)}};Tee.Area.prototype=new Tee.CustomSeries;Tee.HorizArea=function(a,d){Tee.Area.call(this,a,d);this.yMandatory=!1};Tee.HorizArea.prototype=new Tee.Area;Tee.Donut=
function(a,d){Tee.Pie.call(this,a,d);this.donut=50};Tee.Donut.prototype=new Tee.Pie;Tee.Gantt=function(a,d){Tee.Series.call(this,a,d);this.yMandatory=!1;this.dateFormat="mediumDate";this.hover.enabled=!0;this.hover.round.x=this.hover.round.y=8;this.colorEach="yes";this.data.start=this.data.values;this.data.x=[];this.data.end=[];this.height=70;this.margin=new m(6,6);var b=this.format;b.shadow.visible=!0;b.round.x=b.round.y=8;b.stroke.fill="black";b.gradient.visible=!0;var e=new n,c;this.addRandom=
function(a){a||(a=5);var b=this.data;b.x.length=a;b.start.length=a;b.end.length=a;if(0<a)for(var c,d,e=0;e<a;e++)b.x[e]=e,c=12*Math.random()|0,d=10*Math.random()|0,b.start[e]=new Date(2012,c,d),5>c&&(c=5+(7*Math.random()|0)),b.end[e]=new Date(2012,c,d+10*Math.random())};this.bounds=function(a,b){if(this.isNull(a))return!1;this.calc(a,b);b.y-=0.5*c;b.width=this.data.end?this.mandatoryAxis.calcSize(this.data.end[a]-this.data.start[a]):0;b.height=c;return!0};this.add=function(a,b,c,d){var e=this.data;
e.labels.push(b);e.x.push(a);e.start.push(c);e.end.push(d)};this.clicked=function(a){var b=this.data.values.length,c;for(c=0;c<b;c++)if(this.bounds(c,e)&&e.contains(a))return c;return-1};this.draw=function(){var a=this.data.values.length,d,g,j=this.hover,i=j.fill;c=this.notmandatory.calcSize(0.01*this.height);for(d=0;d<a;d++)this.bounds(d,e)&&(g=j.enabled&&this.over===d?j:b,g.fill=this.getFillStyle(e,this.getFill(d,g)),g.rectangle(e));j.fill=i};this.horizMargins=function(a){a.x=this.margin.x;a.y=
this.margin.y};this.minYValue=function(){return this.parent.minXValue.call(this)-0.5};this.maxYValue=function(){return this.parent.maxXValue.call(this)+0.5};this.minXValue=function(){return Math.min.apply({},this.data.start)};this.maxXValue=function(){return Math.max.apply({},this.data.end)}};Tee.Gantt.prototype=new Tee.Series;Tee.Gantt.prototype.parent=Tee.Series.prototype;Tee.Bubble=function(a,d){Tee.PointXY.call(this,a,d);var b=this.pointer;b.colorEach=!0;b.style="sphere";b.format.gradient.visible=
!0;b.format.gradient.direction="radial";this.inflate=!0;this.data.radius=[];this.addRandom=function(a){var b=this.data;a||(a=5);b.values.length=a;b.x=null;b.radius=[];b.radius.length=a;if(0<a)for(var d=0;d<a;d++)b.values[d]=1E3*Math.random(),b.radius[d]=50+150*Math.random()}};Tee.Bubble.prototype.initZ=function(){this.parent.prototype.initZ.call(this);this.format.marks.z=this.format.z-1};Tee.Bubble.prototype=new Tee.PointXY;Tee.Bubble.prototype.getSize=function(a){a=this.data.radius?this._vertAxis.calcSize(this.data.radius[a]):
0;this.pointer.width=a;this.pointer.height=a};Tee.Bubble.prototype.horizMargins=function(a){this.calcWidth=function(a){this.getSize(a);var a=1+0.5*this.pointer.width,b=this.pointer.format.stroke;""!==b.fill&&(a+=b.size);return a};this.pointer.visible&&this.inflate&&(a.x=this.calcWidth(0),a.y=this.calcWidth(this.count()-1))};Tee.Bubble.prototype.vertMargins=function(a){this.calcHeight=function(a){this.getSize(a);var a=1+0.5*this.pointer.height,b=this.pointer.format.stroke;""!==b.fill&&(a+=b.size);
return a};if(this.pointer.visible&&this.inflate){var d,b,e=0,c=0,f=this.count(),h={x:0,y:0};if(0<f){this.calc(0,h);d=b=h.y;for(var g=1;g<f;g++)this.calc(g,h),h.y<d?e=g:h.y>b&&(c=g);a.x=this.calcHeight(c);a.y=this.calcHeight(e)}}};Tee.Volume=function(a,d){Tee.Bar.call(this,a,d);this.barStyle="line";this.colorEach=this.marks.visible=!1;var b=this.format;b.shadow.visible=!1;b.gradient.visible=!1;b.stroke.fill=""};Tee.Volume.prototype=new Tee.Bar;Tee.Candle=function(a,d){Tee.PointXY.call(this,a,d);var b=
this.format;b.z=0.5;b.depth=0.1;this.pointer.width=7;this.pointer.format.stroke.visible=!1;var e=this.higher=this.pointer.format;e.fill="green";var c=this.lower=new Tee.Format(this.chart);c.fill="red";c.stroke.visible=!1;this.style="candle";this.setChart=function(a,b){var d=Tee.PointXY.prototype.setChart;d(a,b);c.setChart(b)};this.draw=function(){var a=this.data,d=a.values.length,g,j=new m,i=this.pointer,k=0.5*i.width,l,q,y,p=this.mandatoryAxis,u,s,t=this.chart.ctx,n,r;t.z=b.z+0.5*b.depth;for(g=0;g<
d;g++)if(!this.isNull(g)&&(this.calc(g,j),r=j.x,l=p.calc(a.open[g]),q=p.calc(a.high[g]),y=p.calc(a.low[g]),j.y>l?(u=l,s=j.y-l,n=c):(u=j.y,s=l-u,n=e),"bar"==this.style?(t.beginPath(),t.moveTo(r,q),t.lineTo(r,y),t.moveTo(r-k,l),t.lineTo(r,l),t.moveTo(r,j.y),t.lineTo(r+k,j.y),n.stroke.prepare(n.fill),t.stroke()):(n.depth=k/100,n.z=b.z+0.5*b.depth-0.5*n.depth,l={x:r-k,y:u,width:i.width,height:s},"cylinder"===this.pointer.style?n.cylinder(l,1,!0):n.cube(l),n.draw(t,null,l),this.hover.enabled&&this.over==
g&&this.hover.rectangle(r-k,u,i.width,s)),"openclose"!=this.style&&(q<u||y>u+s)))t.z=b.z+0.5*b.depth,t.beginPath(),t.moveTo(r,u),t.lineTo(r,q),t.moveTo(r,u+s),t.lineTo(r,y),this.hover.enabled&&this.over==g?this.hover.stroke.prepare(n.fill):n.stroke.prepare(n.fill),t.stroke()};this.minYValue=function(){return 0<this.data.low.length?Math.min.apply({},this.data.low):0};this.maxYValue=function(){return 0<this.data.high.length?Math.max.apply({},this.data.high):0};this.addRandom=function(a){var b=this.data;
a||(a=10);b.values.length=a;b.close=b.values;b.open?b.open.length=a:b.open=Array(a);b.high?b.high.length=a:b.high=Array(a);b.low?b.low.length=a:b.low=Array(a);if(0<a)for(var c=25+100*Math.random(),d,e=0;e<a;e++)d=b.open[e]=c,c=b.close[e]=c+25*Math.random()-12.5,b.high[e]=Math.max(d,c)+15*Math.random(),b.low[e]=Math.min(d,c)-15*Math.random()}};Tee.Candle.prototype=new Tee.PointXY;Tee.Candle.prototype.clicked=function(a){var d=this.pointer.width,b=this.mandatoryAxis,e=this.notmandatory,c=this.data,
f=c.values.length,h=new n,g,j,i;h.width=d;for(g=0;g<f;g++)if(!this.isNull(g)&&(h.x=e.calc(g)-0.5*d,j=b.calc(c.open[g]),i=b.calc(c.close[g]),h.y=j>i?i:j,h.height=Math.abs(j-i),h.contains(a)))return g;return-1};Tee.Candle.prototype.vertMargins=function(){};Tee.Polar=function(a,d){var b,e;function c(a,b,c){if(a.visible){var d=a.axisPos;a.axisPos=b;a.startPos=c-i;a.endPos=c+i;b=a.z;a.z=1-0.5*a.chart.walls.back.size-0.1;a.drawAxis();a.axisPos=d;a.z=b}}function f(a,c){var d=a.width,f=a.height;b=a.x+0.5*
d;e=a.y+0.5*f;i=0.5*Math.min(d,f);c.visible&&c.labels.visible&&(d=c.labels.format.textHeight("W"),i-=d)}Tee.CustomSeries.call(this,a,d);this.pointer.visible=!0;this.rotation=0;this.useOrigin=this._paintWalls=this._paintAxes=!1;this.origin=0;var h={x:0,y:0},g,j=this.format;e=b=0;var i,k=Math.PI/180;j.stroke.fill="black";j.z=0.5;this.calc=function(a,c){var d=this.data,f=d.values[a],g=this.mandatoryAxis,d=k*(this.rotation+(d.x?d.x[a]:360*a/d.values.length)),f=(g.inverted?g.maximum-f:f-g.minimum)*i/(g.maximum-
g.minimum);c.x=b+Math.cos(d)*f;c.y=e+Math.sin(d)*f};this.beforeDraw=function(){var a;f(this.chart.chartRect,this.notmandatory);var d=this.chart.walls;if(d.visible&&(a=d.back,a.visible)){var g=a.format;a=g.z;g.z=1;g.ellipse(b,e,2*i,2*i);g.z=a}if(this.chart.axes.visible){var g=this.notmandatory,h=g.grid.format.stroke,j=this.mandatoryAxis,m=0,n=this.chart.ctx,r,v=10,w=g.rotation||0;if(g.visible&&g.labels.visible){var x={x:0,y:0,width:0,height:0},z=g.labels.format,A=z.textHeight("W"),B=i+0.8*A,v=Math.max(10,
90/(i/A|0));a=z.z;z.z=0.6;for(m=0;360>m;)r=k*(m+w),x.x=b+Math.cos(r)*B,x.y=e+Math.sin(r)*B-0.5*A,z.drawText(x,""+m),m+=v;z.z=a}if(g.visible&&g.grid.visible){a=g.increment||10;n.z=1-0.5*d.back.size-0.1;n.beginPath();for(m=0;360>m;)r=k*(m+w),n.moveTo(b,e),n.lineTo(b+Math.cos(r)*i,e+Math.sin(r)*i),m+=a;h.prepare(h.fill,n);n.stroke()}if(j.visible&&j.grid.visible){m=j.roundMin();h=j.grid.format;r=2*i/(j.maximum-j.minimum);a=h.z;h.z=1-0.5*d.back.size-0.1;for(n.z=h.z;m<j.maximum;)d=(m-j.minimum)*r,h.ellipse(b,
e,d,d),m+=j.increm;h.z=a}c(j,b,e);c(g,e,b)}};this.draw=function(){f(this.chart.chartRect,this.notmandatory);var a=this.data.values.length,c;g=[];for(c=0;c<a;c++)this.isNull(c)||(this.calc(c,h),g.push({x:h.x,y:h.y}));a=g.length;if(0<a){if("bar"==this.style){var d=this.chart.ctx;d.beginPath();for(c=0;c<a;c++)d.moveTo(b,e),d.lineTo(g[c].x,g[c].y);this.format.stroke.prepare(this.format.fill,d);d.stroke()}else j.polygon(g);this.pointer.visible&&this.drawPointers()}};this.minYValue=function(){var a=Tee.Series.prototype.minYValue.call(this);
return this.useOrigin?Math.min(a,this.origin):a};this.maxYValue=function(){var a=this.stackMaxValue();return this.useOrigin?Math.max(a,this.origin):a}};Tee.Polar.prototype=new Tee.CustomSeries;"function"!==typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Tee.PaletteSeries=function(a,d){Tee.Series.call(this,a,d);var b=this.palette;b.colors=Tee.RainbowPalette();var e,c;this._range=this._min=0;this.prepareColors=function(){var a=b.colors,d;c=a.length;
e=Array(c);for(var g=0;g<c;g++)d=a[g].trim(),7==d.length?e[g]={r:parseInt(d.substr(1,2),16),g:parseInt(d.substr(3,2),16),b:parseInt(d.substr(5,2),16),a:0}:"rgb("==d.substr(0,4)&&(d=d.slice(4,d.length-1).split(","),e[g]={r:d[0],g:d[1],b:d[2],a:d[3]||0})};this.getColor=function(a){a=(c-1)*((a-this._min)/this._range)|0;return e[b.inverted?c-1-a:a]};this.legendCount=function(){return this.palette.colors?this.palette.colors.length:0}};Tee.PaletteSeries.prototype=new Tee.Series;Tee.PaletteSeries.prototype.legendColor=
function(a){var d=this.palette,b=d.colors,e=d.inverted;this.chart.legend.inverted&&(e=!e);return d.grayScale?(a=255*a/b.length|0,e&&(a=255-a),"rgb("+a+","+a+","+a+")"):b?b[e?a:this.legendCount()-a-1]:this.format.fill};Tee.PaletteSeries.prototype.legendText=function(a){a=-1+this.legendCount()-a;return(this._min+a*this._range/(this.palette.colors.length-1)).toFixed(this.decimals)};var D=0,r,w,H,E="undefined"!==typeof document&&document.all?!0:!1;Tee.DOMTip={show:function(a,d){r||(r=document.createElement("div"),
r.setAttribute("id","teetip1"),r.className="teetip",r.setAttribute("style","padding:5px; margin-left:5px; background-color:#666; border-radius:4px 4px; color:#FFF; z-index:1000;"),document.body.appendChild(r),w=r.style,w.opacity=0,E&&(w.filter="alpha(opacity=0)"));document.onmousemove=this.pos;w.display="block";w.position="absolute";r.innerHTML=a;w.width=d?d+"px":"auto";!d&&E&&(w.width=r.offsetWidth);300<r.offsetWidth&&(w.width="300px");H=parseInt(r.offsetHeight,10)+3;r.timer&&clearInterval(r.timer);
r.timer=setInterval(function(){Tee.DOMTip.fade(1)},10)},pos:function(a){var d=document.documentElement,b=E?a.clientY+d.scrollTop:a.pageY,a=E?a.clientX+d.scrollLeft:a.pageX;0>b-H&&(b=H);0>a&&(a=0);w.top=b-H+"px";w.left=a+3+"px"},fade:function(a){var d=D;if(97!==d&&1===a||0!==d&&-1===a){var b=10;10>97-d&&1==a?b=97-d:10>D&&-1==a&&(b=d);D=d+b*a;w.opacity=0.01*D;E&&(w.filter="alpha(opacity="+D+")")}else clearInterval(r.timer),-1==a&&(w.display="none",document.onmousemove=null)},hide:function(){r&&(clearInterval(r.timer),
r.timer=setInterval(function(){Tee.DOMTip.fade(-1)},10))}}}).call(this);
